### ISSUE TITLE
升级0.4.2后无法控制风管机

### ISSUE THREAD

**Issue by ymj0424** [wuwentao/midea_ac_lan#126]
### HA版本

2024.6.1

### 集成版本

0.4.2

### 设备类型及型号

Air Conditioner 230J6225 (44204)

### 使用的App

美的美居

### 问题详细描述

As title

### The logs

2024-06-21 19:44:53.457 ERROR (中央空调三) [midealocal.device] [210006726456147] Error in process message, msg = aa6aac00000000000805bb6000ffff3000ff00000060096009000000c00000000500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000fe
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 363, in parse_message
    self.update_all(status)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 447, in update_all
    update(status)
  File "/config/custom_components/midea_ac_lan/climate.py", line 225, in update_state
    elif preset_mode == PRESET_BOOST:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1231, in schedule_update_ha_state
    self.hass.loop.call_soon_threadsafe(
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 838, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 540, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by lyfqdl** [comment]
同样的问题，可以控制温度，无法开关机。

**Comment by wuwentao** [comment]
@ymj0424 @lyfqdl 感谢反馈bug，请开启debug log
开启debug log的方法参考首页readme，最底下：

 修改 configuration.yaml
```
logger:
  default: warn
  logs:
    custom_components.midea_ac_lan: debug
    midealocal: debug
```
修改后reboot，再操作报错的功能，贴一下报错log前后相关的debug log详情

**Comment by lyfqdl** [comment]
不知道操作对不对
2024-06-23 12:32:36.737 DEBUG (客厅空调) [midealocal.devices.ac] [210006723955447] Received: {'header': 'aa72ac00000000000803', 'body': 'bb6800ffff1080808080050000b20c5a0a00000000000000008000000000000000000000005000020023000000000000000000010000000000000000000000000000000000000400000000000000ff00000000000000313030303030080830300000000000000000', 'message type': '.03', 'body type': '.bb'}
2024-06-23 12:32:36.737 DEBUG (客厅空调) [midealocal.device] [210006723955447] Status update: {'indoor_temperature': 32.5, 'indoor_humidity': 0, 'indirect_wind': False, 'screen_display': False}
2024-06-23 12:32:36.875 DEBUG (客厅空调) [midealocal.devices.ac] [210006723955447] Received: {'header': 'aa3aac00000000000803', 'body': 'bb3000ffff110080000000005266320000000000000101000164045232660004000000000000000000000000000091b2', 'message type': '.03', 'body type': '.bb'}
2024-06-23 12:32:36.876 DEBUG (客厅空调) [midealocal.device] [210006723955447] Status update: {'power': False, 'mode': 2, 'target_temperature': 26.0, 'fan_speed': 102, 'dry': False, 'aux_heating': False, 'boost_mode': False, 'sleep_mode': False, 'eco_mode': False, 'indirect_wind': False, 'screen_display': False}
2024-06-23 12:32:37.037 DEBUG (南卧室空调) [midealocal.device] [211106235933185] Connecting to 192.168.50.52:6444
2024-06-23 12:32:37.070 DEBUG (客厅空调) [midealocal.devices.ac] [210006723955447] Received: {'header': 'aa6aac00000000000803', 'body': 'bb6000ffff3000ff0000004e0c540b000000c0000000050000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e258', 'message type': '.03', 'body type': '.bb'}
2024-06-23 12:32:37.070 DEBUG (客厅空调) [midealocal.device] [210006723955447] Status update: {'outdoor_temperature': 31.5, 'indirect_wind': False, 'screen_display': False}

**Comment by chemelli74** [comment]
Please attach the log as file and don't paste the context in the comment as this way is very hard to read.

**Comment by lyfqdl** [comment]
[Uploading error_log.txt…]()

**Comment by lyfqdl** [comment]
[error_log.txt](https://github.com/user-attachments/files/15944251/error_log.txt)

**Comment by lyfqdl** [comment]
北卧室和南卧室是没有接通电源，实际上是没有问题的。
客厅空调是风管机，0.42版本可以调整温度，开关机没有反应。

**Comment by chemelli74** [comment]
Please downgrade to 0.4.1 vai HACS(don't do any other change to the system) and upload corresponding log.

**Comment by lyfqdl** [comment]
[home-assistant_midea_ac_lan_2024-07-04T08-14-55.635Z.log](https://github.com/user-attachments/files/16095576/home-assistant_midea_ac_lan_2024-07-04T08-14-55.635Z.log)
不知道有没有按要求操作，日志里可能没有有用的信息。

尝试使用[Discord Chat](https://discord.com/invite/ZWdd2fXndn)交流，但无法进入。
![1](https://github.com/wuwentao/midea_ac_lan/assets/16411127/16f612c6-e187-47b3-bded-38132bac599c)

**Comment by lyfqdl** [comment]
日志有用吗？@chemelli74 @wuwentao

**Comment by wuwentao** [comment]
@lyfqdl 抱歉，日志没有用，没有什么有意义的信息。

首先请升级到目前最新的版本，然后根据首页README说明开启midea_ac_lan和midealocal的debug log，重启HA，删除无法添加的设备配置文件

这个xxx是你是设备虚拟ID，你可以使用`cat /config/.storage/midea_ac_lan/xxx.json`查看里面的内容，确保是需要删除的设备，然后再执行`rm -rf /config/.storage/midea_ac_lan/xxx.json`来删除这个配置文件。
同时，也可以删除一个能够添加成功的设备，将一个成功，一个失败的设备分布都删除掉。

然后重新添加这2个设备，然后将debug log再上传一下吧。
主要看看成功和失败的设备具体差异信息吧。

**Comment by bimizx** [comment]
解决了吗，我有同样的问题

**Comment by exat500g** [comment]
美的乐享3代风管机，可以调整温度，但是切换模式无效
[home-assistant_2024-07-18T16-02-17.879Z.log](https://github.com/user-attachments/files/16286030/home-assistant_2024-07-18T16-02-17.879Z.log)

**Comment by exat500g** [comment]
我感觉是协议有问题，使用georgezhao2010/midea_ac_lan的就工作正常，但是georgezhao2010的hacs.json有midea拼写错误，导致hacs下载的时候会出现Unknow Error，我fork并修复了这个错误，然后成功安装上，直接就能正常使用了

**Comment by lyfqdl** [comment]
> 美的乐享3代风管机，可以调整温度，但是切换模式无效 [home-assistant_2024-07-18T16-02-17.879Z.log](https://github.com/user-attachments/files/16286030/home-assistant_2024-07-18T16-02-17.879Z.log)

这个日志有用吗 @wuwentao @chemelli74

**Comment by wuwentao** [comment]
@lyfqdl @ymj0424 @exat500g @bimizx 
请问这个问题是否还存在？请帮忙确认当前issue的状态。

同时请先升级到当前最新的v0.5.7版本，确认是否都ok了，如果仍然不行，**请参考首页readme说明，开启debug log，执行有问题的操作，将完整的debug log以附件上传**，感谢！

**Comment by lyfqdl** [comment]
感谢大佬，好像从0.5.5开始修复了这个问题。
但新版有个问题就是，设备实体会变不可用(还没搞清楚重现规律，有一次是隔了一晚上出现)，重新加载后恢复。  @wuwentao

**Comment by wuwentao** [comment]
@lyfqdl 感谢回复和确认。
那我先close当前issue了。

而设备变不可用，这个必然会有log存在的，因此查看log会显示具体的原因。
后续再观察一下，看看是否还继续出现，如果问题仍然继续出现，可以根据错误提示提交新的issue来解决，同时出现问题的时候，需要开启debug log，并将完整log上传。
