### ISSUE TITLE
TOSHIBA Washer, model: TW-BL80A2CZ(SS), app: TSmartLife

### ISSUE THREAD

**Issue by stylar-maker** [wuwentao/midea_ac_lan#185]
### Device type and model (or SN)

TW-BL80A2CZ(SS)

### The description of new feature

Hello,

I'm trying to use `midea_ac_lan` with Home Assistant, and it seems it might work with a TOSHIBA washing machine connected to the network via WiFi. The issue is how to navigate the login process when the washing machine uses the TSmartLife app, which isn't available here. Is there a way to integrate the washing machine into HA for local control or to display its entities?

Thank you in advance for any assistance!

![Snímek obrazovky 2024-06-29 115604](https://github.com/wuwentao/midea_ac_lan/assets/174092509/01346b69-3f34-4e87-91b2-28138eb755f4)
![Snímek obrazovky 2024-06-29 155917](https://github.com/wuwentao/midea_ac_lan/assets/174092509/ef569d88-c760-4b58-892a-d561ece03e69)
![Snímek obrazovky 2024-06-29 155941](https://github.com/wuwentao/midea_ac_lan/assets/174092509/1ca1c7c2-d324-47da-bf4c-455ad2140052)

**Comment by rokam** [comment]
Try adding it manually with the data provided by "list all appliances". It should work with the default keys.

I believe Toshiba uses the same backend of ``````Midea Air, can you try that option with your TSmartLife account?

**Comment by stylar-maker** [comment]
I tried the offered login options, but none of them work for me.

When I want to use 'Configure manually,' a 'New appliance' window pops up. I don't know where to get the TOKEN and KEY. It keeps saying 'Token or Key in an incorrect format.'

**Comment by chemelli74** [comment]
@stylar-maker we need debug log to look at to know what happens

**Comment by stylar-maker** [comment]
2024-07-01 17:27:48.912 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'midea_ac_lan' at custom_components/midea_ac_lan/config_flow.py, line 127: return load_json(record_file, default={}) (offender: /usr/src/homeassistant/homeassistant/util/json.py, line 78: with open(filename, mode="rb") as fdesc:), please create a bug report at https://github.com/wuwentao/midea_ac_lan/issues
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
response = await handler(request)
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
result = await handler(request, **request.match_info)
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
return await func(self, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 70, in wrapper
return await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure
result = await self._async_configure(flow_id, user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
result = await self._async_handle_step(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
result: _FlowResultT = await getattr(flow, method)(user_input)
File "/config/custom_components/midea_ac_lan/config_flow.py", line 300, in async_step_auto
storage_device = self._load_device_config(device_id)
File "/config/custom_components/midea_ac_lan/config_flow.py", line 127, in _load_device_config
return load_json(record_file, default={})

**Comment by stylar-maker** [comment]
Full log attached.
[home-assistant_2024-07-01T15-35-23.132Z.log](https://github.com/user-attachments/files/16056084/home-assistant_2024-07-01T15-35-23.132Z.log)

**Comment by rokam** [comment]
Hi @stylar-maker can you leave the key and token empty?

Also, to provide us more info:
Please add the following to configuration.yaml , restart HA, and post the log:

```
logger:
  default: warning
  logs:
    custom_components.midea_ac_lan: debug
    midealocal: debug
```

Note: it is better to drag the log into the comment (which will add it as an attachment) and not copy paste as it is hard to read logs in GitHub.

And add diagnostics (menu configuration -> integration -> midea_ac_lan -> download diagnostics )

**Comment by stylar-maker** [comment]
Hi, here are the requested logs attached according to your instructions.
[home-assistant_2024-07-03T14-12-50.799Z.log](https://github.com/user-attachments/files/16086280/home-assistant_2024-07-03T14-12-50.799Z.log)
[config_entry-hacs-83bf92936eaf32996ebe3f1827385ea7.json](https://github.com/user-attachments/files/16086282/config_entry-hacs-83bf92936eaf32996ebe3f1827385ea7.json)

**Comment by stylar-maker** [comment]
Hi, I tried adding the device during the logging process, but I can't get any further.

Discover automatically - I can't log in, I only have a TSmartLife account.
Configure manually - I don't have the token and key.
List of appliances only - the device is found as supported, but clicking 'Submit' does nothing.

**Comment by stylar-maker** [comment]
I finnaly managed to add the washing machine (protocols V1 and V2 are working) and I can see entities, although they don't appear to be functional.
<img width="230" alt="washer" src="https://github.com/wuwentao/midea_ac_lan/assets/174092509/a94ffe3d-76b5-4f3d-bb50-04724efb7f85">

**Comment by wuwentao** [comment]
> I finnaly managed to add the washing machine (protocols V1 and V2 are working) and I can see entities, although they don't appear to be functional. <img alt="washer" width="230" src="https://private-user-images.githubusercontent.com/174092509/345512060-a94ffe3d-76b5-4f3d-bb50-04724efb7f85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjQ0NzEsIm5iZiI6MTcyMDA2NDE3MSwicGF0aCI6Ii8xNzQwOTI1MDkvMzQ1NTEyMDYwLWE5NGZmZTNkLTc2YjUtNGYzZC1iYjUwLTA0NzI0ZWZiN2Y4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQwMzM2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzRkMjAyNWM4NTgxNTcyZTIxZDRhMGM2MjgwNjhjNzRkY2YyMDU0ZmNkOGNjMGUxMTZhOGI5ZTZjOWRiMzlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sh2isF-eynjkdE9Go8fS1oDLkJgcCu7JY4XumTuNrPo">
> 
> updated logs: [home-assistant_2024-07-03T16-28-22.530Z.log](https://github.com/user-attachments/files/16087978/home-assistant_2024-07-03T16-28-22.530Z.log) [config_entry-hacs-83bf92936eaf32996ebe3f1827385ea7.json](https://github.com/user-attachments/files/16087980/config_entry-hacs-83bf92936eaf32996ebe3f1827385ea7.json)

No, you can't add device with V1 or V2, as your device type is V3, so you can only add it with V3 type.
if you add it with v2 type, you can't control your device.
as the protocol is error......

so please don't manual change the protocol version, and you need to add device with the right protocol v3 version.
if it can't add pass, it should be some error exist.
the error log can show the readon.
