### ISSUE TITLE
Dehumidifier unavailable after setup: CapabilitiesFailed

### ISSUE THREAD

**Issue by keyluke** [wuwentao/midea_ac_lan#215]
### HA core version

2024.7.1

### Integration version

0.5

### Device type and model

Dehumidifier 00000Q18 (0) (Ariston DEOS16s)

### Used App

MSmartHome

### The description of problem

After correctly setup the device, it appears as unavailable in Homeassistant.
The following exception is raised from the log (debug enabled as stated from the README): CapabilitiesFailed.

### The logs

```
2024-07-09 12:27:10.026 ERROR (Deumidificatore) [midealocal.device] [31885837206704] Unknown error : /srv/homeassistant/lib/python3.12/site-packages/midealocal/device.py, 221
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.12/site-packages/midealocal/device.py", line 221, in connect
    self.get_capabilities(wait_response=True)
  File "/srv/homeassistant/lib/python3.12/site-packages/midealocal/device.py", line 329, in get_capabilities
    raise CapabilitiesFailed
midealocal.device.CapabilitiesFailed
```

**Comment by 22kW** [comment]
Same here (Midea dehumidifiers):

Logger: midealocal.device
Quelle: /usr/local/lib/python3.12/site-packages/midealocal/device.py:239
Erstmals aufgetreten: 11:58:55 (1516 Vorkommnisse)
Zuletzt protokolliert: 13:09:10

[152832116353363] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 221
[152832116339431] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 221
[153931627967640] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 221
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 221, in connect
    self.get_capabilities(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 329, in get_capabilities
    raise CapabilitiesFailed
midealocal.device.CapabilitiesFailed

**Comment by chemelli74** [comment]
Hi all, please confirm the last working version ( if any ).

Also we need full debug log; so please add the following to `configuration.yaml` , restart HA, and post the log:
```yaml
logger:
  default: warning
  logs:
    custom_components.midea_ac_lan: debug
    midealocal: debug
 ```
Note: it is better to drag the log into the comment (which will add it as an attachment) and not copy paste as it is hard to read logs in GitHub.

**Comment by erikgieseler** [comment]
Same here. 0.4.3 working fine.
[_homeassistant_logs.txt](https://github.com/user-attachments/files/16145281/_homeassistant_logs.txt)

**Comment by sanderlv** [comment]
After updat to 0.5 same error


Logger: midealocal.device
Source: /usr/local/lib/python3.12/site-packages/midealocal/device.py:239
First occurred: 22:27:57 (1 occurrences)
Last logged: 22:27:57

[146235046613512] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 219
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 219, in connect
    self.refresh_status(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 344, in refresh_status
    raise SocketException
midealocal.exceptions.SocketException

**Comment by rokam** [comment]
https://github.com/rokam/midea-local/pull/212 fixes the capability issue

**Comment by sanderlv** [comment]
> https://github.com/rokam/midea-local/pull/212 fixes the capability issue

I am sorry, but I still have 2 device malfunction 

Logger: midealocal.device
Source: /usr/local/lib/python3.12/site-packages/midealocal/device.py:239
First occurred: 18:26:29 (1 occurrences)
Last logged: 18:26:29

[146235046613512] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 219
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 219, in connect
    self.refresh_status(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 344, in refresh_status
    raise SocketException
midealocal.exceptions.SocketException

**Comment by chemelli74** [comment]
This issue is about a different error. Please open a new one.
