### ISSUE TITLE
Unable to serialize to JSON. Bad data found

### ISSUE THREAD

**Issue by HamsenBender** [wuwentao/midea_ac_lan#221]
### HA core version

2024.7.1

### Current integration version

0.5.0

### Last known working integration version

0.4.3

### Device type and model

Air Conditioner 00000Q1A (44204)

### Used App

Home Assistant

### The description of problem

All devices and entities show as unavaillable

### The logs

Logger: homeassistant.components.websocket_api.messages
Bron: components/websocket_api/messages.py:243
integratie: Home Assistant WebSocket API (documentatie, problemen)
Eerst voorgekomen: 08:20:47 (4 gebeurtenissen)
Laatst gelogd: 08:27:12

Unable to serialize to JSON. Bad data found at $.event.a.climate.ac_bureau.a.modes=dict[str, bool](<class 'types.GenericAlias'>
Unable to serialize to JSON. Bad data found at $.event.a.climate.ac_eve.a.modes=dict[str, bool](<class 'types.GenericAlias'>
Unable to serialize to JSON. Bad data found at $.event.a.climate.ac_jan.a.modes=dict[str, bool](<class 'types.GenericAlias'>
Unable to serialize to JSON. Bad data found at $.event.c.climate.ac_bureau.+.a.modes=dict[str, bool](<class 'types.GenericAlias'>

**Comment by HamsenBender** [comment]
Addiitonal errors

2024-07-10 09:08:22.033 ERROR (Airco Slaapkamer Eve) [midealocal.device] [146235046581270] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 221
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 221, in connect
    self.get_capabilities(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 329, in get_capabilities
    raise CapabilitiesFailed
midealocal.device.CapabilitiesFailed
2024-07-10 09:08:22.045 ERROR (Airco Slaapkamer Jan) [midealocal.device] [145135534954211] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 221
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 221, in connect
    self.get_capabilities(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 329, in get_capabilities
    raise CapabilitiesFailed
midealocal.device.CapabilitiesFailed
2024-07-10 09:08:22.057 ERROR (Bureau) [midealocal.device] [142936511698615] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 221
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 221, in connect
    self.get_capabilities(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 329, in get_capabilities
    raise CapabilitiesFailed
midealocal.device.CapabilitiesFailed
2024-07-10 09:09:00.299 ERROR (SyncWorker_10) [O365.connection] Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/calendars/xxxx | Error Message: Id is malformed. | Error Code: 
2024-07-10 09:09:00.301 WARNING (MainThread) [custom_components.o365.calendar] Error getting calendar events - 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/calendars/xxxx | Error Message: Id is malformed.
2024-07-10 09:09:00.479 ERROR (SyncWorker_16) [O365.connection] Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/calendars/xxxx | Error Message: Id is malformed. | Error Code: 
2024-07-10 09:09:00.481 WARNING (MainThread) [custom_components.o365.calendar] Error getting calendar events - 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/calendars/xxxx | Error Message: Id is malformed.
2024-07-10 09:09:07.612 ERROR (Airco Slaapkamer Jan) [midealocal.device] [145135534954211] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 221
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 221, in connect
    self.get_capabilities(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 329, in get_capabilities
    raise CapabilitiesFailed
midealocal.device.CapabilitiesFailed
2024-07-10 09:09:07.613 ERROR (Airco Slaapkamer Eve) [midealocal.device] [146235046581270] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 221
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 221, in connect
    self.get_capabilities(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 329, in get_capabilities
    raise CapabilitiesFailed
midealocal.device.CapabilitiesFailed
2024-07-10 09:09:07.632 ERROR (Bureau) [midealocal.device] [142936511698615] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 221
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 221, in connect
    self.get_capabilities(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 329, in get_capabilities
    raise CapabilitiesFailed
midealocal.device.CapabilitiesFailed

**Comment by HamsenBender** [comment]
Not resolved in 0.5.1

**Comment by chemelli74** [comment]
> Not resolved in 0.5.1

Always attach a  fresh debug log

**Comment by HamsenBender** [comment]
Hi, after upgrade to 0.5.2, devices are still unavailable.
When I reload the integration they sometimes come online, but go unavailable again after a while.

2024-07-11 15:38:26.445 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:38:26.549 DEBUG (Airco Slaapkamer Eve) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:38:34.739 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:38:41.495 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:38:41.992 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:38:42.110 DEBUG (Airco Slaapkamer Eve) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:38:50.139 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:38:52.029 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:38:57.041 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:39:12.010 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:39:12.140 DEBUG (Airco Slaapkamer Eve) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:39:20.169 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:39:22.054 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:13.222 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:13.277 DEBUG (Airco Slaapkamer Eve) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:20.828 ERROR (Bureau) [midealocal.device] [142936511698615] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 219
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 219, in connect
    self.refresh_status(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 344, in refresh_status
    raise SocketException
midealocal.exceptions.SocketException
2024-07-11 15:40:20.830 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:23.233 ERROR (Airco Slaapkamer Jan) [midealocal.device] [145135534954211] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 219
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 219, in connect
    self.refresh_status(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 344, in refresh_status
    raise SocketException
midealocal.exceptions.SocketException
2024-07-11 15:40:23.234 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:24.462 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:28.183 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:31.364 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:32.322 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:35.834 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:38.771 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:40.842 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:43.301 DEBUG (Airco Slaapkamer Eve) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:45.849 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:50.856 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:54.476 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:57.354 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:58.205 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:58.367 ERROR (Airco Slaapkamer Eve) [midealocal.device] [146235046581270] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 219
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 219, in connect
    self.refresh_status(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 344, in refresh_status
    raise SocketException
midealocal.exceptions.SocketException
2024-07-11 15:40:58.368 DEBUG (Airco Slaapkamer Eve) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:40:59.535 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:02.011 DEBUG (Airco Slaapkamer Eve) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:02.352 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:03.189 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:03.211 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:08.217 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:08.813 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:09.491 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:10.087 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:13.224 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:14.039 DEBUG (Airco Slaapkamer Eve) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:14.499 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:17.899 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:18.230 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:19.506 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:23.237 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:24.357 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:24.513 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:29.520 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:30.130 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:32.042 DEBUG (Airco Slaapkamer Eve) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:34.526 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:38.244 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:39.533 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:40.113 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:44.062 DEBUG (Airco Slaapkamer Eve) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:44.543 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:45.120 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:47.599 DEBUG (Airco Slaapkamer Eve) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:47.933 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:49.550 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:50.127 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:53.259 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:54.381 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:54.556 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:58.268 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:59.564 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:41:59.623 DEBUG (Airco Slaapkamer Eve) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:00.223 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:03.275 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:03.487 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:04.572 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:05.146 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:08.282 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:09.578 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:09.932 DEBUG (Airco Slaapkamer Jan) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:10.153 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:14.587 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:15.162 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:17.624 DEBUG (Airco Slaapkamer Eve) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:19.593 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:20.169 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>
2024-07-11 15:42:23.293 DEBUG (Bureau) [custom_components.midea_ac_lan.climate] Climate update_state self: <class 'custom_components.midea_ac_lan.climate.MideaACClimate'>

[home-assistant_midea_ac_lan_2024-07-11T13-44-58.544Z.log](https://github.com/user-attachments/files/16178086/home-assistant_midea_ac_lan_2024-07-11T13-44-58.544Z.log)

**Comment by HamsenBender** [comment]
And thanks for the effort already made :)

**Comment by chemelli74** [comment]
The error changed, please open a new issue. Thank you
