### ISSUE TITLE
更新版本后空调不可用 (Event loop is closed)

### ISSUE THREAD

**Issue by yyax** [wuwentao/midea_ac_lan#232]
### HA版本

2024.07.2

### 集成版本

0.5.2

### 之前可正常使用的集成版本

0.4.3

### 设备类型及型号

Air Conditioner 22396315 (44204)

### 使用的App

美的美居

### 问题详细描述

更新好后空调全部不可用

### The logs

日志记录器: midealocal.device
来源: /usr/local/lib/python3.12/site-packages/midealocal/device.py:596
首次出现: 10:43:10 (1 次总计出现)
上次记录: 10:43:10

[211106234224971] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 561
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 561, in run
    self._check_refresh(now)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 538, in _check_refresh
    self.refresh_status()
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 365, in refresh_status
    raise RefreshFailed
midealocal.device.RefreshFailed

**Comment by chemelli74** [comment]
Please attach full debug log

**Comment by yyax** [comment]
[home-assistant.log](https://github.com/user-attachments/files/16190454/home-assistant.log)

**Comment by wuwentao** [comment]
@yyax please check with latest v0.5.3 and update the result, it should be fixed in v0.5.3.
thanks!

**Comment by yyax** [comment]
已修复，谢谢
