### ISSUE TITLE
安装不上

### ISSUE THREAD

**Issue by bimizx** [wuwentao/midea_ac_lan#242]
### HA版本

2024.8.1

### 集成版本

0.5.3

### 之前可正常使用的集成版本

0.4.2

### 设备类型及型号

0000005112239651733170311371X8VX

### 使用的App

美的美居

### 问题详细描述

/config # midealocal discover --host 192.168.1.7 -d
2024-07-17 01:38:57.064 DEBUG (MainThread) [midealocal.discover] All addresses for broadcast: ['192.168.1.7']
2024-07-17 01:38:57.101 DEBUG (MainThread) [midealocal.discover] Received response from ('192.168.1.7', 6445): 837000c8200f00005a5a0111b8007a8000000000aa3826011107181490ec850000c000000000000000000180000000007bad2eb4ade49788c2184ca927f0e65c279699f8d09e622a6c99e8a22d52526e3940d031276331ebeaadf58016f24782fccfbde16d3c62960063c728868fb43c9cb7c1fce2d7d28bfb664b6b258259fde4f89c2bca2fa68e4ae88b85742141624bdfb3e16e33d88768cc4c3d0658937d96fbcce99f70c976413c2f05f60f82e737fad4168934d8060145786cc49f9f79a1df762ebea063de29132ca9c4b93604
2024-07-17 01:38:57.107 DEBUG (MainThread) [midealocal.discover] Declassified reply: 0701a8c02c19000030303030303035313132323339363531373333313730333131333731583856580d6d696465615f61635f313337310000bf0502000000000000000000ac00010000000000fcdf00e94060150034062334010300000000000000000000000000000000000000000000000000000000000000000000
2024-07-17 01:38:57.107 DEBUG (MainThread) [midealocal.discover] Found a supported device: {'device_id': 211106241309840, 'type': 172, 'ip_address': '192.168.1.7', 'port': 6444, 'model': '22396517', 'sn': '0000005112239651733170311371X8VX', 'protocol': 3}
2024-07-17 01:39:02.113 INFO (MainThread) [cli] Found 1 devices.
Traceback (most recent call last):
  File "/usr/local/bin/midealocal", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midealocal/cli.py", line 319, in main
    cli.run(namespace)
  File "/usr/local/lib/python3.12/site-packages/midealocal/cli.py", line 196, in run
    asyncio.run(self.namespace.func())
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midealocal/cli.py", line 76, in discover
    else await self._get_keys(device["device_id"])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midealocal/cli.py", line 57, in _get_keys
    cloud = await self._get_cloud()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midealocal/cli.py", line 44, in _get_cloud
    raise ElementMissing("Missing required parameters for cloud request.")
midealocal.exceptions.ElementMissing: Missing required parameters for cloud request.
/config # 

2024-07-17 01:39:13.718 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration midea_ac_lan: cannot import name 'default_keys' from 'midealocal.cloud' (/usr/local/lib/python3.12/site-packages/midealocal/cloud.py)

添加上空调无法控制，安装时显示无法加载配置向导: {"message":"Invalid handler specified"}，手动安装midea-local，还是不行

**Comment by chemelli74** [comment]
Hi, seems you are manually installing components and selecting the wrong versions

**Comment by wuwentao** [comment]
你一次反馈了3个不同的问题：
1. 添加成功了，不能控制
2. 安装时显示无法加载配置向导
3. 手动安装midea-local，还是不行（请问手工安装这个意义是什么？需要了解是干嘛的）

所以，你的问题到底是什么？你提供的报错的debug log对应的是什么问题？你标题写的安装不上……
请先理清你的逻辑和思路，并准确反馈你的问题，并提供对应的debug log等，提交issue的模板里面有详细说明，标题，内容，日志，完全是牛头不对马嘴啊。
