### ISSUE TITLE
空调无法控制

### ISSUE THREAD

**Issue by GavinIves** [wuwentao/midea_ac_lan#270]
### 集成版本

0.5.4

### 之前可正常使用的集成版本

无

### 设备类型及型号

HL1PRO Air Conditioner 22040057 (44204) HE1PRO Air Conditioner 22040055 (44204) 小冰棒2代柜机 Air Conditioner 22270063 (32773)

### 使用的App

美的美居

### 问题详细描述

控制空调显示broken pipe
<img width="416" alt="image" src="https://github.com/user-attachments/assets/bd6ba519-36ac-4cd3-acfc-eece84c67ec8">
下面是两块报错的日志 因为日志太大 不能全部贴出来 截取了两块疑似出问题的地方

### The logs

2024-08-07 17:11:47.013 DEBUG (蒸烤箱) [midealocal.devices.bf] [210006728939381] Received: {'header': 'aa45bff2000000001203', 'body': '0100000000000000000000000000000000000000000000000000230000000001000000000000000000000000000698010104000000000000000000', 'message type': '.03', 'body type': '.01'}
2024-08-07 17:11:47.013 DEBUG (蒸烤箱) [midealocal.device] [210006728939381] Status update: {'door': False, 'status': 'PowerSave', 'time_remaining': 0, 'current_temperature': 35, 'tank_ejected': False, 'water_change_reminder': False}
2024-08-07 17:11:49.665 DEBUG (洗衣机) [midealocal.device] [211106241012006] Sending: {'header': 'aa0bdb00000000000003', 'body': '03', 'message type': '.03', 'body type': '.03'}
2024-08-07 17:11:49.806 DEBUG (洗衣机) [midealocal.devices.db] [211106241012006] Received: {'header': 'aa47db00000000000003', 'body': '030000001f012003030102040100000004010000db58314c0000000e0a0000c0ffffffffffffffffffffffffffffff0101ffffffffff0000ffff08ffff', 'message type': '.03', 'body type': '.03'}
2024-08-07 17:11:49.806 DEBUG (洗衣机) [midealocal.device] [211106241012006] Status update: {'power': False, 'start': False, 'washing_data': bytearray(b'\x00\x1f\x01 \x03\x03\x01\x02\x04\x01\x00\x00\x00'), 'progress': 'Wash', 'time_remaining': None}
2024-08-07 17:11:51.639 DEBUG (干衣机) [midealocal.device] [210006728895741] Sending: {'header': 'aa0bdc00000000000003', 'body': '03', 'message type': '.03', 'body type': '.03'}
2024-08-07 17:11:51.814 DEBUG (干衣机) [midealocal.devices.dc] [210006728895741] Received: {'header': 'aa41dc00000000000003', 'body': '0300000002000000000200000000000001640000dc34384c00000000000100000000004000000001000000000000030000000000000000', 'message type': '.03', 'body type': '.03'}
2024-08-07 17:11:51.814 DEBUG (干衣机) [midealocal.device] [210006728895741] Status update: {'power': False, 'start': False, 'washing_data': bytearray(b'\x00\x02\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00'), 'progress': 'Prog1', 'time_remaining': None}
2024-08-07 17:11:52.020 DEBUG (蒸烤箱) [midealocal.device] [210006728939381] Sending: {'header': 'aa0bbf00000000001203', 'body': '01', 'message type': '.03', 'body type': '.01'}
2024-08-07 17:11:52.192 DEBUG (蒸烤箱) [midealocal.devices.bf] [210006728939381] Received: {'header': 'aa45bff3000000001203', 'body': '0100000000000000000000000000000000000000000000000000230000000001000000000000000000000000000698010104000000000000000000', 'message type': '.03', 'body type': '.01'}
2024-08-07 17:11:52.192 DEBUG (蒸烤箱) [midealocal.device] [210006728939381] Status update: {'door': False, 'status': 'PowerSave', 'time_remaining': 0, 'current_temperature': 35, 'tank_ejected': False, 'water_change_reminder': False}
2024-08-07 17:11:52.485 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-08-07 17:11:54.350 ERROR (MainThread) [custom_components.xiaomi_miot.humidifier] Mijia Mist-Free Humidifier 3 Pro(xiaomi.humidifier.airmx): Got MiioException while fetching the state: Unable to discover the device 10.123.100.68, mapping: {'humidifier.on': {'siid': 2, 'piid': 1}, 'humidifier.fault': {'siid': 2, 'piid': 2}, 'humidifier.mode': {'siid': 2, 'piid': 3}, 'humidifier.target_humidity': {'siid': 2, 'piid': 6}, 'humidifier.water_level': {'siid': 2, 'piid': 7}, 'humidifier.overwet_protect': {'siid': 2, 'piid': 10}, 'humidifier.automatic_air_drying': {'siid': 2, 'piid': 12}, 'humidifier.air_dry_remain_time': {'siid': 2, 'piid': 13}, 'wash.wash_water_tank': {'siid': 19, 'piid': 1}, 'descale.on': {'siid': 17, 'piid': 1}, 'descale.remain_time': {'siid': 17, 'piid': 2}, 'descale.clean_water_tank': {'siid': 17, 'piid': 3}, 'clean.on': {'siid': 16, 'piid': 1}, 'clean.remain_time': {'siid': 16, 'piid': 2}, 'clean.clean_water_tank': {'siid': 16, 'piid': 3}, 'filter.filter_life_level': {'siid': 18, 'piid': 1}, 'indicator_light.on': {'siid': 15, 'piid': 1}, 'indicator_light.mode': {'siid': 15, 'piid': 2}, 'indicator_light.brightness': {'siid': 15, 'piid': 3}, 'indicator_light.auto_lights_off': {'siid': 15, 'piid': 4}, 'alarm': {'siid': 14, 'piid': 1}, 'alarm.auto_alarm_off': {'siid': 14, 'piid': 2}, 'delay': {'siid': 12, 'piid': 1}, 'delay.delay_time': {'siid': 12, 'piid': 2}, 'delay.delay_remain_time': {'siid': 12, 'piid': 3}, 'physical_controls_locked': {'siid': 11, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.temperature': {'siid': 3, 'piid': 2}}, max_properties: 10/28
2024-08-07 17:11:54.519 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Connect call failed ('::', 443, 0, 0)]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 471, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/base.py", line 529, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Connect call failed ('::', 443, 0, 0)]
2024-08-07 17:11:54.718 WARNING (ImportExecutor_0) [homeassistant.const] CONDUCTIVITY was used from aqara_gateway, this is a deprecated constant which will be removed in HA Core 2025.6. Use UnitOfConductivity.MICROSIEMENS instead, please report it to the author of the 'aqara_gateway' custom integration
2024-08-07 17:11:54.812 DEBUG (洗衣机) [midealocal.device] [211106241012006] Sending: {'header': 'aa0bdb00000000000003', 'body': '03', 'message type': '.03', 'body type': '.03'}
2024-08-07 17:11:54.953 DEBUG (洗衣机) [midealocal.devices.db] [211106241012006] Received: {'header': 'aa47db00000000000003', 'body': '030000001f012003030102040100000004010000db58314c0000000e0a0000c0ffffffffffffffffffffffffffffff0101ffffffffff0000ffff08ffff', 'message type': '.03', 'body type': '.03'}
2024-08-07 17:11:54.953 DEBUG (洗衣机) [midealocal.device] [211106241012006] Status update: {'power': False, 'start': False, 'washing_data': bytearray(b'\x00\x1f\x01 \x03\x03\x01\x02\x04\x01\x00\x00\x00'), 'progress': 'Wash', 'time_remaining': None}
2024-08-07 17:11:56.563 ERROR (MainThread) [homeassistant.components.homeassistant_alerts.coordinator] Error requesting homeassistant_alerts data: Cannot connect to host alerts.home-assistant.io:443 ssl:default [None]
2024-08-07 17:11:56.564 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'
2024-08-07 17:11:56.823 DEBUG (干衣机) [midealocal.device] [210006728895741] Sending: {'header': 'aa0bdc00000000000003', 'body': '03', 'message type': '.03', 'body type': '.03'}
2024-08-07 17:11:57.006 DEBUG (干衣机) [midealocal.devices.dc] [210006728895741] Received: {'header': 'aa41dc00000000000003', 'body': '0300000002000000000200000000000001640000dc34384c00000000000100000000004000000001000000000000030000000000000000', 'message type': '.03', 'body type': '.03'}
2024-08-07 17:11:57.006 DEBUG (干衣机) [midealocal.device] [210006728895741] Status update: {'power': False, 'start': False, 'washing_data': bytearray(b'\x00\x02\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00'), 'progress': 'Prog1', 'time_remaining': None}
2024-08-07 17:11:57.198 DEBUG (蒸烤箱) [midealocal.device] [210006728939381] Sending: {'header': 'aa0bbf00000000001203', 'body': '01', 'message type': '.03', 'body type': '.01'}
2024-08-07 17:11:57.376 DEBUG (蒸烤箱) [midealocal.devices.bf] [210006728939381] Received: {'header': 'aa45bff4000000001203', 'body': '0100000000000000000000000000000000000000000000000000230000000001000000000000000000000000000698010104000000000000000000', 'message type': '.03', 'body type': '.01'}
2024-08-07 17:11:57.376 DEBUG (蒸烤箱) [midealocal.device] [210006728939381] Status update: {'door': False, 'status': 'PowerSave', 'time_remaining': 0, 'current_temperature': 35, 'tank_ejected': False, 'water_change_reminder': False}
2024-08-07 17:11:59.988 DEBUG (洗衣机) [midealocal.device] [211106241012006] Sending: {'header': 'aa0bdb00000000000003', 'body': '03', 'message type': '.03', 'body type': '.03'}

2024-08-07 17:12:28.186 DEBUG (蒸烤箱) [midealocal.device] [210006728939381] Sending: {'header': 'aa0bbf00000000001203', 'body': '01', 'message type': '.03', 'body type': '.01'}
2024-08-07 17:12:28.263 DEBUG (干衣机) [midealocal.devices.dc] [210006728895741] Received: {'header': 'aa41dc00000000000003', 'body': '0300000002000000000200000000000001640000dc34384c00000000000100000000004000000001000000000000030000000000000000', 'message type': '.03', 'body type': '.03'}
2024-08-07 17:12:28.263 DEBUG (干衣机) [midealocal.device] [210006728895741] Status update: {'power': False, 'start': False, 'washing_data': bytearray(b'\x00\x02\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00'), 'progress': 'Prog1', 'time_remaining': None}
2024-08-07 17:12:28.363 DEBUG (蒸烤箱) [midealocal.devices.bf] [210006728939381] Received: {'header': 'aa45bffa000000001203', 'body': '0100000000000000000000000000000000000000000000000000230000000001000000000000000000000000000698010104000000000000000000', 'message type': '.03', 'body type': '.01'}
2024-08-07 17:12:28.363 DEBUG (蒸烤箱) [midealocal.device] [210006728939381] Status update: {'door': False, 'status': 'PowerSave', 'time_remaining': 0, 'current_temperature': 35, 'tank_ejected': False, 'water_change_reminder': False}
2024-08-07 17:12:28.891 DEBUG (SyncWorker_12) [midealocal.device] [210006728890230] Sending: {'header': 'aa23ac00000000000802', 'body': '40415b66000000300088000000000000000000000000001619', 'message type': '.02', 'body type': '.40'}
2024-08-07 17:12:28.892 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139941966261856] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 924, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 724, in async_set_temperature
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/climate.py", line 200, in set_temperature
    self._device.set_target_temperature(
  File "/usr/local/lib/python3.12/site-packages/midealocal/devices/ac/__init__.py", line 391, in set_target_temperature
    self.build_send(message)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 287, in build_send
    self.send_message(msg)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 258, in send_message
    self.send_message_v3(data, msg_type=MSGTYPE_ENCRYPTED_REQUEST)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 280, in send_message_v3
    self.send_message_v2(data)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 265, in send_message_v2
    self._socket.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-08-07 17:12:30.849 DEBUG (洗衣机) [midealocal.device] [211106241012006] Sending: {'header': 'aa0bdb00000000000003', 'body': '03', 'message type': '.03', 'body type': '.03'}
2024-08-07 17:12:30.965 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'
2024-08-07 17:12:30.991 DEBUG (洗衣机) [midealocal.devices.db] [211106241012006] Received: {'header': 'aa47db00000000000003', 'body': '030000001f012003030102040100000004010000db58314c0000000e0a0000c0ffffffffffffffffffffffffffffff0101ffffffffff0000ffff08ffff', 'message type': '.03', 'body type': '.03'}
2024-08-07 17:12:30.992 DEBUG (洗衣机) [midealocal.device] [211106241012006] Status update: {'power': False, 'start': False, 'washing_data': bytearray(b'\x00\x1f\x01 \x03\x03\x01\x02\x04\x01\x00\x00\x00'), 'progress': 'Wash', 'time_remaining': None}
2024-08-07 17:12:33.270 DEBUG (干衣机) [midealocal.device] [210006728895741] Sending: {'header': 'aa0bdc00000000000003', 'body': '03', 'message type': '.03', 'body type': '.03'}
2024-08-07 17:12:33.369 DEBUG (蒸烤箱) [midealocal.device] [210006728939381] Sending: {'header': 'aa0bbf00000000001203', 'body': '01', 'message type': '.03', 'body type': '.01'}
2024-08-07 17:12:33.481 DEBUG (干衣机) [midealocal.devices.dc] [210006728895741] Received: {'header': 'aa41dc00000000000003', 'body': '0300000002000000000200000000000001640000dc34384c00000000000100000000004000000001000000000000030000000000000000', 'message type': '.03', 'body type': '.03'}
2024-08-07 17:12:33.481 DEBUG (干衣机) [midealocal.

**Comment by GavinIves** [comment]
[home-assistant_2024-08-07T09-17-01.358Z.log](https://github.com/user-attachments/files/16536666/home-assistant_2024-08-07T09-17-01.358Z.log)
日志如上

**Comment by GavinIves** [comment]
发现了原因 是因为使用了美的美居的家庭共享 当另一个账号控制了一次这些设备 某些参数会变化 可能是token成他的账号的token 此时我这里的控制就失效了 及时我再去用我的账号控制也没有用了 只能重新添加进HA 我觉得这个问题需要确认一下 以防止后续因为token过期导致过一段时间就要重新添加刷新一次token 虽然我暂时还没有遇到token过期

**Comment by wuwentao** [comment]
@GavinIves 应该不是你说的这个问题，这不应该影响。
看起来可能是和其他的一个bug有关系，请先升级到当前最新的v0.5.6版本，然后重新试试v0.5.6版本上是否还有这个问题。
并反馈一下v0.5.6上使用的结果是否恢复正常。
如果仍然不行，还是有错误，还请重新上传一下v0.5.6上执行操作报错的完整debug log

**Comment by GavinIves** [comment]
已升级 目前看貌似是解决了这个问题 等我观察几天来汇报
