### ISSUE TITLE
Periodic disconnections, reloading integration resolves

### ISSUE THREAD

**Issue by phidauex** [wuwentao/midea_ac_lan#306]
### HA core version

2024.8.3

### Current integration version

0.5.7

### Last known working integration version

none

### Device type and model

Dehumidifier 00000Q12 (41377)

### Working mobile app

SmartHome

### The description of problem

Thanks for the great local integration - appreciate you taking the project over.

My issue is that the integration connects to my Midea dehumidifier, as does the SmartHome app (US version), and all controls work and behave as expected. However, after between 10 minutes and a few hours, the integration will disconnect from the dehumidifier and indicate "unavailable". Occasionally it will come back on its own (only to disconnect a short while later), but usually it stays disconnected from this point forward.

Reloading the integration, or restarting HomeAssistant will cause it to successfully reconnect, at least for a period of time. Restarting the dehumidifier on its own does not cause it to reconnect.

Below is one full cycle of the activity, ending in the disconnection notification. I see three connection attempts, 10 seconds apart. Could this be too short for some of these devices? Could we allow it to try 5 times, 30 seconds apart, for instance?

Behavior over the last few days:
![image](https://github.com/user-attachments/assets/1d2d2dc9-9e4f-43cd-836b-b9cd4b855a6e)

Longest stretch 8 hours, shortest stretch only 4 minutes.

### The logs

```
2024-09-04 10:03:08.331 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connecting to 10.0.20.66:6444
2024-09-04 10:03:08.337 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connected
2024-09-04 10:03:08.337 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Enabling device
2024-09-04 10:03:08.337 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Status update: {'available': True}
2024-09-04 10:03:08.338 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Authentication handshaking
2024-09-04 10:03:08.389 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Authentication success
2024-09-04 10:03:08.389 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Sending: {'header': 'aa1da1000000000000a0', 'body': '00000000000000000000000000000000000000', 'message type': '.a0', 'body type': '.00'}
2024-09-04 10:03:08.563 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Received: {'header': 'aa2aa1000000000008a0', 'body': '00a1030016000000000000000000000000000000000000000000000000000000', 'message type': '.a0', 'body type': '.00'}
2024-09-04 10:03:08.564 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Device protocol version: 8
2024-09-04 10:03:08.564 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Sending: {'header': 'aa20a100000000000003', 'body': '418100ff00000000000000000000000000000000138a', 'message type': '.03', 'body type': '.41'}
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] [150633093756827] Received: {'header': 'aa23a100000000000803', 'body': 'c80101287f7f003700000000000000643b5c00000000001301', 'message type': '.03', 'body type': '.c8'}
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: None,                                      water_level: 50, tank_full_calculated: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'tank_full': False, 'power': True}, tank_full: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 50, tank_full_calculated: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'tank_full': False, 'power': True, 'child_lock': False}, tank_full: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 50, tank_full_calculated: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'tank_full': False, 'power': True, 'child_lock': False, 'mode': 'Manual'}, tank_full: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 50, tank_full_calculated: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'tank_full': False, 'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low'}, tank_full: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 50, tank_full_calculated: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'tank_full': False, 'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False}, tank_full: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 50, tank_full_calculated: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'tank_full': False, 'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55}, tank_full: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 50, tank_full_calculated: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'tank_full': False, 'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False}, tank_full: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 50, tank_full_calculated: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'tank_full': False, 'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0}, tank_full: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'tank_full': False, 'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0, 'water_level_set': '100'}, tank_full: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'tank_full': False, 'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0, 'water_level_set': '100', 'current_humidity': 59}, tank_full: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'tank_full': False, 'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0, 'water_level_set': '100', 'current_humidity': 59, 'current_temperature': 21.0}, tank_full: False
2024-09-04 10:03:08.675 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Status update: {'tank_full': False, 'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0, 'water_level_set': '100', 'current_humidity': 59, 'current_temperature': 21.0}
2024-09-04 10:03:38.737 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Sending: {'header': 'aa20a100000000000803', 'body': '418100ff000000000000000000000000000000001409', 'message type': '.03', 'body type': '.41'}

Log truncated, duplicate 30sec connection records between these points

2024-09-04 10:09:10.865 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Sending: {'header': 'aa20a100000000000803', 'body': '418100ff000000000000000000000000000000001f29', 'message type': '.03', 'body type': '.41'}
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] [150633093756827] Received: {'header': 'aa23a100000000000803', 'body': 'c80101287f7f003700000000000000643c5c00000000001f72', 'message type': '.03', 'body type': '.c8'}
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual'}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low'}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0, 'water_level_set': '100'}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0, 'water_level_set': '100', 'current_humidity': 60}, tank_full: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device - tank: 0, tank_full: False,                                      water_level: 100, tank_full_calculated: False
2024-09-04 10:09:10.986 DEBUG (Dehumidifier) [midealocal.devices.a1] Device after - new_status: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0, 'water_level_set': '100', 'current_humidity': 60, 'current_temperature': 21.0}, tank_full: False
2024-09-04 10:09:10.987 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Status update: {'power': True, 'child_lock': False, 'mode': 'Manual', 'fan_speed': 'Low', 'swing': False, 'target_humidity': 55, 'anion': False, 'tank': 0, 'water_level_set': '100', 'current_humidity': 60, 'current_temperature': 21.0}
2024-09-04 10:09:41.043 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Sending: {'header': 'aa20a100000000000803', 'body': '418100ff0000000000000000000000000000000020d6', 'message type': '.03', 'body type': '.41'}
2024-09-04 10:10:11.075 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Sending: {'header': 'aa20a100000000000803', 'body': '418100ff000000000000000000000000000000002188', 'message type': '.03', 'body type': '.41'}
2024-09-04 10:10:41.108 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Sending: {'header': 'aa20a100000000000803', 'body': '418100ff00000000000000000000000000000000226a', 'message type': '.03', 'body type': '.41'}
2024-09-04 10:11:11.142 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Heartbeat timed out
2024-09-04 10:11:11.142 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connecting to 10.0.20.66:6444
2024-09-04 10:11:21.152 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connection timed out
2024-09-04 10:11:21.153 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connecting to 10.0.20.66:6444
2024-09-04 10:11:31.163 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connection timed out
2024-09-04 10:11:31.163 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connecting to 10.0.20.66:6444
2024-09-04 10:11:41.174 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connection timed out
2024-09-04 10:11:41.174 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Enabling device
2024-09-04 10:11:41.174 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Status update: {'available': False}
2024-09-04 10:11:41.175 ERROR (Dehumidifier) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 515, in run
    raise CannotConnect
midealocal.exceptions.CannotConnect
```

Complete debug log (includes the event occurring a few times)
[home-assistant.log](https://github.com/user-attachments/files/16910241/home-assistant.log)

**Comment by xiasi0** [comment]
+1

**Comment by wuwentao** [comment]
just want to confirm, you have missed  the same error `raise CannotConnect`  as #276  ?
as you don't provide full debug log, and also not  error in your log msg.

**Comment by jshatch** [comment]
This is happening to me also. I'll get you my logs as well if you wish.

**Comment by phidauex** [comment]
@wuwentao Apologies, I can see you desperately asking for debug logs. Yes, it does look like I'm getting the same error as #276 . 

```
2024-09-03 23:10:46.125 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Sending: {'header': 'aa20a100000000000803', 'body': '418100ff0000000000000000000000000000000012d4', 'message type': '.03', 'body type': '.41'}
2024-09-03 23:11:06.147 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Heartbeat timed out
2024-09-03 23:11:06.148 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connecting to 10.0.20.66:6444
2024-09-03 23:11:16.149 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connection timed out
2024-09-03 23:11:16.150 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connecting to 10.0.20.66:6444
2024-09-03 23:11:26.158 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connection timed out
2024-09-03 23:11:26.159 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connecting to 10.0.20.66:6444
2024-09-03 23:11:36.162 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Connection timed out
2024-09-03 23:11:36.162 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Enabling device
2024-09-03 23:11:36.162 DEBUG (Dehumidifier) [midealocal.device] [150633093756827] Status update: {'available': False}
2024-09-03 23:11:36.164 ERROR (Dehumidifier) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 515, in run
    raise CannotConnect
midealocal.exceptions.CannotConnect
```

Below is a full debug logs, one with all the homeassistant log content. I've updated the main post to include the content as well. Still pasting an excerpt from the log to help others identify if it is the same issue.

[home-assistant.log](https://github.com/user-attachments/files/16910207/home-assistant.log)

**Comment by wuwentao** [comment]
@phidauex @xiasi0 @jshatch 
it should be fix with latest release v0.5.8, please upgrade and confirm the result.
close current issue, if the same issue still exist, we can continue update in current issue or reopen it later.

**Comment by xiasi0** [comment]
@wuwentao 已经安装了v0.5.8。48小时后来回复测试结果。感谢您的修复！

**Comment by wuwentao** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> @wuwentao has installed v0.5.8. Will reply with test results after 48 hours. Thanks for the fix!

v0.5.8 have a high cpu issue, v0.5.9 is pending and waitting for approve, once it done , new version will available

**Comment by sanderlv** [comment]
I have noticed this since latest update to v0.5.9. It might have been there before, but only now the humidity is going up and the device turns on more often. Then I can not turn it off until I reload the specific device integration.

**Comment by wuwentao** [comment]
@sanderlv 

it should be a knonw issue with latest v0.5.9, the status refresh will be delay for 1-30 seconds after you change the status.
already have a fix and still waiting for new issue test result.
once got a confirmation, will publish a new release to fix it.


**if you want to manual test with the latest changes to confirm with it, below is the steps:**

test methdod:
update to latest v0.5.9 and replace `device.py` in **midea-local** lib with latest changes in this URL https://github.com/rokam/midea-local/blob/f0b25dc271aa7de45746d76165e3c7b76d078cf3/midealocal/device.py

detail steps:

1. if you are using HAOS, you should install Add-on [Advanced SSH & Web Terminal] and disable [Protected Mode], once it done, you can ssh to your HAOS, and enter docker in HAOS `docker exec -it homeassistant /bin/bash`, contiune the step to check `midea-local` install path
2. if you not using HAOS, just check `midea-local` install path as the next step
3. get `midea-local` install path with command `pip show midea-local`, it will show info for you, for example, my location is `Location: /usr/local/lib/python3.12/site-packages`
4. then we can replace local `/usr/local/lib/python3.12/site-packages/midealocal/device.py` with the latest code changes from the URL `https://github.com/rokam/midea-local/blob/f0b25dc271aa7de45746d76165e3c7b76d078cf3/midealocal/device.py`
   i just using vi to delete the full file and paste the content to it `vi /usr/local/lib/python3.12/site-packages/midealocal/device.py` , once the file is opend, the bottom will show you `1/690 0%`, 1 mean line 1, and 690 mean total 690 lines(based on your local installed version), you can press `690` + `dd` to delete all the content in this file, once it deleted, you will see `[[Modified] 1/1 100%]` at the bottom, press `i` to insert mode, copy the file content and paste all the content to it (from your ssh Terminal app), finally, press `:wq` to save and exit 
 5. reboot HA and test with it, confirm whether it fix your bug


**If the testing process is too complicated, just ignore it and we will publish a fix in future.**
the main purpose is replace the device.py with latest code and test it before publish

**Comment by wuwentao** [comment]
please have a try with latest v0.6.0.
will be publish in some hours later, PR already there and waitting for approve.
