### ISSUE TITLE
MDV Wi-Fi Controller K86EB (0) does not work out

### ISSUE THREAD

**Issue by SikaiGGMU** [wuwentao/midea_ac_lan#308]
### HA版本

2024.09.1

### 集成版本

0.5.7

### 之前可正常使用的集成版本

0.3.22

### 设备类型及型号

MDV Wi-Fi Controller K86EB (0)

### 使用的App

美的美居

### 问题详细描述

I just switched from the integration from georgezhao2010, and I found my three MDV Wi-Fi Controller K86EB (0)s does NOT work with the new one.  Maybe my devices are a little bit old,  and I can NOT scan any information with msmart-ng, either 

### The logs

msmart-ng query 192.168.3.10 --auto
INFO:msmart.cli:Discovering 192.168.3.10 on local network.
INFO:msmart.cloud:Using Midea cloud server: https://mp-prod.appsmb.com (China: False).
INFO:msmart.lan:Creating new connection to 192.168.3.10:6444.
INFO:msmart.lan:Authenticating with 192.168.3.10:6444.
INFO:msmart.lan:Authenticating with 192.168.3.10:6444.
INFO:msmart.lan:Authentication with 192.168.3.10:6444 successful. Expiration: 2024-09-08T20:50:30+00:00, Local key: 7d87a4cf5645bb7d57e248d7629694eb30aac952bb5db133e6a2123a191dacd8
ERROR:msmart.discover:Device class Device has not implemented refresh().
ERROR:msmart.cli:Device is not supported.

**Comment by chemelli74** [comment]
Hi @SikaiGGMU , any update from your side ?

**Comment by SikaiGGMU** [comment]
python3 -m midealocal.cli discover -d --host 192.168.3.44
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/midealocal/cli.py", line 24, in <module>
    from midealocal.device import (
  File "/usr/local/lib/python3.11/dist-packages/midealocal/device.py", line 11, in <module>
    from typing_extensions import deprecated
ModuleNotFoundError: No module named 'typing_extensions'

**Comment by chemelli74** [comment]
Which version of the library are you using ?

**Comment by wuwentao** [comment]
@SikaiGGMU you can install midea_ac_lan in your HA device, once it done, you can discovery your device via web UI.
if there is still error exist, you can enable debug log via readme document and upload the full debug log to us.
if there is no any response for a long time, we will conside to close it as no error exist now.

**Comment by SikaiGGMU** [comment]
> Which version of the library are you using ?

I am using debian 12, and I keep updating my system.

**Comment by wuwentao** [comment]
> > Which version of the library are you using ?
> 
> I am using debian 12, and I keep updating my system.

could you help to answer our question ? 
we don't care about your OS or update.

currently, you are using our midea_ac_lan integration, and you have reported a bug with it.
unfortunely, you didn't provide any error info, also not provided any debug log.
so, please back to your issue and this midea_ac_lan.

we have post the solution for you.
if you still think you want to fix error, please provide all the details with the issue template.
I'm sorry, we don't want to watste time with unnecessary  info.

**Comment by SikaiGGMU** [comment]
> > > Which version of the library are you using ?
> > 
> > 
> > I am using debian 12, and I keep updating my system.
> 
> could you help to answer our question ? we don't care about your OS or update.
> 
> currently, you are using our midea_ac_lan integration, and you have reported a bug with it. unfortunely, you didn't provide any error info, also not provided any debug log. so, please back to your issue and this midea_ac_lan.
> 
> we have post the solution for you. if you still think you want to fix error, please provide all the details with the issue template. I'm sorry, we don't want to waste time with unnecessary info.

I think the version I am using is clearly stated in the bug report (之前可正常使用的集成版本

0.3.22).

**Comment by SikaiGGMU** [comment]
> > > Which version of the library are you using ?
> > 
> > 
> > I am using debian 12, and I keep updating my system.
> 
> could you help to answer our question ? we don't care about your OS or update.
> 
> currently, you are using our midea_ac_lan integration, and you have reported a bug with it. unfortunely, you didn't provide any error info, also not provided any debug log. so, please back to your issue and this midea_ac_lan.
> 
> we have post the solution for you. if you still think you want to fix error, please provide all the details with the issue template. I'm sorry, we don't want to waste time with unnecessary info.

I think the version I am using is clearly stated in the stanza of "之前可正常使用的集成版本" of the bug report  (之前可正常使用的集成版本).

0.3.22).

**Comment by SikaiGGMU** [comment]
I am afraid it would be hard for me to frequently switch between 0.5.x and 0.3.22, since I kind of "lost" my device in the 0.5.x version in the early try, and I HAD to restore my entire HA in order to get my device back.

**Comment by wuwentao** [comment]
> I am afraid it would be hard for me to frequently switch between 0.5.x and 0.3.22, since I kind of "lost" my device in the 0.5.x version in the early try, and I HAD to restore my entire HA in order to get my device back.

what's your expected result for this issue?  I don't understand it.

**we just need: what's the error and what's the detail.**

if not, I'm sorry, no on can help with you for this issue.

**Comment by SikaiGGMU** [comment]
> > I am afraid it would be hard for me to frequently switch between 0.5.x and 0.3.22, since I kind of "lost" my device in the 0.5.x version in the early try, and I HAD to restore my entire HA in order to get my device back.
> 
> what's your expected result for this issue? I don't understand it.
> 
> **we just need: what's the error and what's the detail.**
> 
> if not, I'm sorry, no on can help with you for this issue.

 I was just elucidating the fact. Apparently, this new fork is not backwards compatible, and an art project is supposed to be backwards compatible. Also, I can live with the old version.  
Lastly, still need to compliment, great work!

**Comment by wuwentao** [comment]
@SikaiGGMU  I can understand what you said.

unfortunely, it's no possible, it's not control by us, HA also not support it with some version changes(I'm not mean all the HA version upgrade, only some important changes that not backwards compatible)

not only for us, like apple iOS, you also can't support downgrade to old version, why ? as your config have upgrade to new version, only new version know the old format. unfortunely, new version don't know which old version you will downgrade to......

so I will consider there is no any info can be provide by this issue, and I will close it.
sorry.
