### ISSUE TITLE
Device auth failed with input config

### ISSUE THREAD

**Issue by petepall** [wuwentao/midea_ac_lan#320]
### Current integration version

0.59

### Last known working integration version

0.57

### Device type and model

Ariston airco

### Working mobile app

Ariston app

### The description of problem

One of my airco units is not working anymore. I removed the entity and try to put it back and receive the following message “ Device auth failed with input config”

what am I missing here as no auth info is being requested

### The logs

2024-09-22 23:19:53.889 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args (PosixPath('/config/.storage/midea_ac_lan/152832116830366.json'),) inside the event loop by custom integration 'midea_ac_lan' at custom_components/midea_ac_lan/config_flow.py, line 150: with record_file.open(encoding="utf-8") as f: (offender: /config/custom_components/midea_ac_lan/config_flow.py, line 150: with record_file.open(encoding="utf-8") as f:), please create a bug report at https://github.com/wuwentao/midea_ac_lan/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
response = await handler(request)
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
result = await handler(request, **request.match_info)
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
return await func(self, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
return await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure
result = await self._async_configure(flow_id, user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
result = await self._async_handle_step(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
result: _FlowResultT = await getattr(flow, method)(user_input)
File "/config/custom_components/midea_ac_lan/config_flow.py", line 496, in async_step_auto
storage_device = self._load_device_config(device_id)
File "/config/custom_components/midea_ac_lan/config_flow.py", line 150, in _load_device_config
with record_file.open(encoding="utf-8") as f:
2024-09-22 23:19:53.916 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/.storage/midea_ac_lan/152832116830366.json',) inside the event loop by custom integration 'midea_ac_lan' at custom_components/midea_ac_lan/config_flow.py, line 151: return load_json(f.name, default={}) (offender: /usr/src/homeassistant/homeassistant/util/json.py, line 74: with open(filename, mode="rb") as fdesc:), please create a bug report at https://github.com/wuwentao/midea_ac_lan/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
response = await handler(request)
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
result = await handler(request, **request.match_info)
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
return await func(self, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
return await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure
result = await self._async_configure(flow_id, user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
result = await self._async_handle_step(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
result: _FlowResultT = await getattr(flow, method)(user_input)
File "/config/custom_components/midea_ac_lan/config_flow.py", line 496, in async_step_auto
storage_device = self._load_device_config(device_id)
File "/config/custom_components/midea_ac_lan/config_flow.py", line 151, in _load_device_config
return load_json(f.name, default={})
2024-09-22 23:19:57.432 ERROR (MainThread) [custom_components.midea_ac_lan.config_flow] Unable to authenticate with provided key and token.
Traceback (most recent call last):
File "/config/custom_components/midea_ac_lan/config_flow.py", line 706, in async_step_manually
dm.authenticate()
File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 250, in authenticate
raise AuthException
midealocal.device.AuthException

2024-09-22 23:23:50.469 ERROR (MainThread) [custom_components.midea_ac_lan.config_flow] Unable to authenticate with provided key and token.
Traceback (most recent call last):
File "/config/custom_components/midea_ac_lan/config_flow.py", line 706, in async_step_manually
dm.authenticate()
File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 250, in authenticate
raise AuthException
midealocal.device.AuthException

**Comment by wuwentao** [comment]
@petepall  there is still a device config cache in storage `/config/.storage/midea_ac_lan/152832116830366.json`
you can login to your HA device via ssh or web ssh add-on, `rm -rf /config/.storage/midea_ac_lan/`
then rerun the device discover and add step.

if there is still error exist, please enable the debug log both for midea-local and midea_ac_lan(refer to README document)
and repeat the discovery/add step, once the error exist, download the full debug log and attach it as a file to current PR.

**Comment by petepall** [comment]
@wuwentao I removed the file and tried to add it. Initially I continued to hit the same issue.
I then manually created the json file but did not enter a token and key. When I than added the device again it connected.

so for the moment all is working again.

**Comment by wuwentao** [comment]
@petepall  so it should works now.
in addition, you don't need to manual create the json file, just discovery device and add it, once it done ,this file will be created with the same name
