### ISSUE TITLE
FSD40THR风扇控制错误

### ISSUE THREAD

**Issue by xiasi0** [wuwentao/midea_ac_lan#321]
### HA版本

2024.9.2

### 集成版本

0.5.9

### 之前可正常使用的集成版本

0.5.9

### 设备类型及型号

实际型号：FSD40THR，HA显示型号：Fan 56011CB4 (0)

### 使用的App

美的美居

### 问题详细描述

0.5.9版本之前开关控制还正常，0.5.9版本中开关变成了瞬时开关点击打开后立马就关闭了。摇头控制也不正常不能打开摇头，摇头控制在所有版本中都不正常。模式选择在所有版本中也不正常。产品的SN:0000FA51156011CB43C161102252D3J8
希望您有时间能修复一下！谢谢

### The logs

[home-assistant_midea_ac_lan_2024-09-23T02-48-54.705Z.log](https://github.com/user-attachments/files/17092282/home-assistant_midea_ac_lan_2024-09-23T02-48-54.705Z.log)

**Comment by wuwentao** [comment]
问题大概看了看，应该还是超时导致的问题，控制命令没有发送成功，我明后天先修复一下

**Comment by wuwentao** [comment]
@xiasi0 

是否可以在发布之前，先协助测试一下是否解决了问题？

具体的测试方法：
需要更新mide-local这个python库, 使用修改后的device.py替换你本地安装的device.py，操作流程

1. 如果你是HAOS安装，需要ssh登录HAOS（安装Advanced SSH & Web Terminal这个【加载项】(英文叫Add-on)，同时关闭其中的【保护模式】
然后就可以ssh登录HAOS，或者直接用这个加载项的网页版登录HAOS了。然后在ssh中执行`docker exec -it homeassistant /bin/bash`即可登录docker，就可以继续后面查找和修改midea-local的流程。。。。
3. 如果不是HAOS，使用的其他模式，只需要查找midea-local这个python库安装在哪里即可。
4. 查找midea-local的安装路径: `pip show midea-local` 显示信息会有安装路径，例如我的显示`Location: /usr/local/lib/python3.12/site-packages`
5. 修改midea-local源码:  使用 `https://github.com/rokam/midea-local/blob/20488c7bb7fd7e747d54ad4541e9ff63349b1d61/midealocal/device.py` 这个文件的内容替换你本地安装的`device.py`文件即可。
方法可能特别多，例如可以使用scp或者其他文件替换法，我自己一般直接使用vi修改，例如： `vi /usr/local/lib/python3.12/site-packages/midealocal/device.py` 打开以后，最底下会显示类似`1/690 0%`，说明当前在文件第一行，文件总共有690行（以你的为准，实际行数根据你安装的版本相应修改即可），先按数字`690`然后紧接着快速按二个`dd`，即可删除整个文件的所有内容，删除成功后最底下会显示`[[Modified] 1/1 100%]`, 然后按字母`i`键进入插入模式，复制`https://github.com/rokam/midea-local/blob/20488c7bb7fd7e747d54ad4541e9ff63349b1d61/midealocal/device.py`这个文件的完整内容，ssh终端软件里面点右键，粘贴，即可，默认显示在最后一行是return ret即可，然后先按`ESC`退出插入模式（如有错误，重复执行xxx数字加dd重来），最后必须按`:wq`来保存退出即可。
HAOS的修改麻烦一些，其他安装模式可能可以直接使用root用户或者其他工具替换文件即可，修改完成以后，只需要重启HA就行了，验证修改是否解决了当前存在的问题。

如果认为流程太麻烦，实在搞不定就算了，随后等review/approve以后，发布新版再测试吧。
或者想尝试，反馈具体不会操作的地方和遇到的问题，再沟通解决也行，总之目的就是用新的`device.py`替换目前安装的`device.py`即可。
在发布之前，先测试一下是否解决了所有问题

**Comment by xiasi0** [comment]
好的，我会配合测试

**Comment by xiasi0** [comment]
https://github.com/rokam/midea-local/blob/20488c7bb7fd7e747d54ad4541e9ff63349b1d61/midealocal/device.py
更新了这个文件，还是一样呢
开关时瞬时的打开后立马关闭，摇头只能关不能开。模式没有一个是正确的😂
这是日志请查看：
[home-assistant_midea_ac_lan_2024-09-24T23-28-29.279Z.log](https://github.com/user-attachments/files/17122143/home-assistant_midea_ac_lan_2024-09-24T23-28-29.279Z.log)

**Comment by wuwentao** [comment]
@xiasi0 
还请帮忙再次验证一下，操作流程相同，但是使用当前最新的修改：
https://github.com/rokam/midea-local/blob/f0b25dc271aa7de45746d76165e3c7b76d078cf3/midealocal/device.py

如果还有其他error log，也请帮忙提供一下完整的debug log，这个问题是修改其他bug引入的，希望能一并解决其他问题。
我这边的AC设备无法复现这个问题，所以只能麻烦帮忙测试一下，并反馈结果和debug log，感谢

**Comment by xiasi0** [comment]
不行呢。f0b25dc271aa7de45746d76165e3c7b76d078cf3这个739行的复制进去重启后集成直接挂了加载不上去集成，这是开启调试的内核完整日志
[home-assistant_2024-09-26T13-56-00.172Z.log](https://github.com/user-attachments/files/17149874/home-assistant_2024-09-26T13-56-00.172Z.log)
--------------------------------------------------------------------------------------------------------------------------------------------
重新复制进去20488c7bb7fd7e747d54ad4541e9ff63349b1d61这个690行的也不能恢复了，集成依然是挂掉的加载不上。这是690行的完整日志。
[home-assistant_2024-09-26T14-05-49.546Z.log](https://github.com/user-attachments/files/17149896/home-assistant_2024-09-26T14-05-49.546Z.log)
@wuwentao

**Comment by xiasi0** [comment]
```
2024-09-26 22:18:18.542 ERROR (ImportExecutor_0) [homeassistant.loader] Unexpected exception importing platform custom_components.midea_ac_lan.config_flow
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/config/custom_components/midea_ac_lan/__init__.py", line 33, in <module>
from midealocal.device import DeviceType, MideaDevice, ProtocolVersion
File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 686
"""Attributes."""
^
SyntaxError: unterminated triple-quoted string literal (detected at line 690)
2024-09-26 22:18:18.545 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.midea_ac_lan.config_flow',) inside the event loop by integration 'config' at homeassistant/components/config/config_entries.py, line 179: return await super()._post_impl(request, data) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1296: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+config%22
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
response = await handler(request)
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
result = await handler(request, **request.match_info)
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
return await func(self, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
return await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
return await self._post_impl(request, data)
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
return await super()._post_impl(request, data)
2024-09-26 22:18:18.546 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.midea_ac_lan.config_flow
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/config/custom_components/midea_ac_lan/__init__.py", line 33, in <module>
from midealocal.device import DeviceType, MideaDevice, ProtocolVersion
File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 686
"""Attributes."""
^
SyntaxError: unterminated triple-quoted string literal (detected at line 690)
2024-09-26 22:18:18.546 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration midea_ac_lan: Exception importing custom_components.midea_ac_lan.config_flow
```
完了卸载重新安装也不行了，集成都添加不了了😂😂😂😂

**Comment by wuwentao** [comment]
@xiasi0 这个错误应该是粘贴时格式出问题了。
文件本身没问题，我确认是好的，其他人也今天测试过解决了AC设备的刷新问题，但是FA设备我还不确定，所以需要进一步验证一下。

另外，你这个错误的核心原因是粘贴的py文件有点问题，应该删除一下内容，重新粘贴，重启即可。
不会影响HA 之外的其他集成。
所以，这个device.py重新删除，复制粘贴再试试重启。

**Comment by xiasi0** [comment]
我再试试哈，先别走哈@wuwentao😁

**Comment by xiasi0** [comment]
重新替换后可以了，但是添加设备提示验证失败呢
![image](https://github.com/user-attachments/assets/0173870a-6058-436c-9e43-3f69c3ba16f7)
没有提示让我登录美的账号呢

**Comment by xiasi0** [comment]
不用进容器吧

**Comment by xiasi0** [comment]
> ```
> cd /config/.storage/midea_ac_lan
> ls
> rm -rf ./*.json   # 或者修改为删除xxx.json
> ```
> 
> 这里会缓存你设备的配置信息，你可以删除里面的xxx.json,然后重新添加就可以了。 也可以从首页readme加入discord chat聊天群组沟通

抱歉，我过不去墙，能不过就不过。抱歉哈🤣

**Comment by wuwentao** [comment]
> 不用进容器吧
删除不需要，容器里面，外面都可以，容器里面也会自动映射

**Comment by wuwentao** [comment]
不用着急，慢慢试试就行，目前已通过其他人测试，确认这个修改已经解决了AC设备，C3设备等问题，等你最终的FA设备测试结果。
如果还有相关的未解决的问题，争取都尽快解决掉，再发布一个新版本即可。
后面就基本慢慢稳定了。

**Comment by xiasi0** [comment]
![image](https://github.com/user-attachments/assets/793d79c8-65f4-4fe1-b3f3-f9e631837768)
![image](https://github.com/user-attachments/assets/a5a089ba-0d7f-45a9-bd62-10d1c8363242)
拿不到token跟key。登录信息也没有缓存。但是确定登录了。美的美居提示我登录了

**Comment by wuwentao** [comment]
@xiasi0 你这个是微波炉设备，确定以前是添加成功的，现在仅仅是删除以后才不能添加了？

你试试添加其他类型的设备看看，手工选一下底下其他设备，尝试添加看看是否可以。
这个无法添加的设备，随后需要提供debug log来确认，你可以开着debug log，逐个都添加一下即可。不成功的最终把debug log单独提供一下吧。

**Comment by xiasi0** [comment]
```日志记录器: midealocal.device
来源: /usr/local/lib/python3.12/site-packages/midealocal/device.py:235
首次出现: 23:45:40 (3 次总计出现)
上次记录: 23:45:47

[210006728410460] Unknown error during connect device
[160528698171210] Unknown error during connect device
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 217, in connect
    self.refresh_status(check_protocol=init)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 372, in refresh_status
    cmds: list = self.build_query()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 524, in build_query
    raise NotImplementedError
NotImplementedError
```
只有一个空调能跳转到下一个页面但是也输入框实际没有token跟key。其它都是直接直接提示没有token跟key。我看日志已经显示有了。
[home-assistant_2024-09-26T15-46-22.796Z.log](https://github.com/user-attachments/files/17151836/home-assistant_2024-09-26T15-46-22.796Z.log)

**Comment by wuwentao** [comment]
@xiasi0 不是大问题，看见你debug log里面报的错误了，这个确实是替换devie.py文件以后导致的问题，这个我明天再改一下就行了。

你先这样操作吧，直接回退v0.5.9，不使用替换的文件，再去添加设备，应该就好了。然后就可以单独替换device.py去测试看行不行了。
如果v0.5.9添加也不行，尝试回退v0.5.7或者v0.5.4，应该v0.5.4是可以的。

不行就明天白天搞吧，大晚上不折腾了，不用担心，以前添加过的设备，删除了仍然是可以添加回来的。

**Comment by xiasi0** [comment]
好的

**Comment by wuwentao** [comment]
@xiasi0 
重新修改了一下，应该用v0.5.9直接替换这个最新修改的device.py也可以添加设备了：
文件如下：
https://github.com/rokam/midea-local/blob/7a9a58abaf6510570033233da238b1900c942e54/midealocal/device.py
避免你来回升级版本了

**Comment by xiasi0** [comment]
![image](https://github.com/user-attachments/assets/cacd51f5-1b45-443f-809d-1c020e5643cd)

设备编号：163827233053934柜机添加失败，如图。
挂机添加成功，风扇添加成功（开关依然是瞬时的打开后立马关闭）。
日志如下：
[home-assistant_2024-09-27T02-49-38.853Z.log](https://github.com/user-attachments/files/17158276/home-assistant_2024-09-27T02-49-38.853Z.log)
@wuwentao

**Comment by wuwentao** [comment]
@xiasi0 添加不成功的我待会再看，先解决状态同步的问题：
你的FA风扇设备看起来是执行命令以后，自身的状态刷新比较慢，导致HA不能立即获取吧。
例如添加成功的AC空调应该问题不大，可以快速刷新，这个大概率是FA风扇设备自身响应慢题导致的问题。


我简单加了一个`time.sleep(0.5)`，执行命令以后临时等待0.5秒，看看是否能够获取到准确的状态吧。
你直接用这个修改的文件替换试试看（注意粘贴后可能无法启动的问题，重新来一次即可）。
[device.py.zip](https://github.com/user-attachments/files/17158540/device.py.zip)

测试方法：
1. 解压缩这个device.py.zip，先直接用这个默认的替换吧。看看这个默认sleep 0.5秒是否能够解决状态刷新的问题。
2. 如果不行，自己搜索`time.sleep(0.5)`,然后将0.5修改为0.8或者1,或者2,看看哪个值是比较合适的值，因为这个值影响所有其他设备，导致其他设备状态刷新也延迟一些了，所以尽可能选一个合理的比较小的值。（注意：你点击风扇的电源开或者关，只需要点击一次即可，不需要反复点击多次，然后观察结果就行，如果不成功，30秒回自动刷新的，因此尽量避免多次反复点击，目前是debug模式，方便查看log）
3. 如果默认的0.5秒就可以正确刷新状态，那么帮忙尝试缩小这个值，例如0.3/0.2/0.1等，看看最小大概哪个值能够可用吧。
4. 帮忙反馈一下结果吧。

**Comment by xiasi0** [comment]
```
time.sleep(0.5)
```
现在风扇开关不会出现打开后立马关闭的情况（但是前端卡片无法使用不会同步任何风扇状态，也不能控制开关）。然后就是在设备页面点击开或者关左下角都会出现参数报错。请查看
```
日志记录器: homeassistant.components.websocket_api.http.connection
来源: components/websocket_api/commands.py:245
集成: Home Assistant WebSocket API ([文档](https://www.home-assistant.io/integrations/websocket_api), [问题](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
首次出现: 22:14:06 (2 次总计出现)
上次记录: 22:14:17

[139724611687984] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 430, in async_handle_turn_on_service
    await self.async_turn_on(percentage, preset_mode, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 439, in async_turn_on
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 165, in turn_on
    self._device.turn_on(fan_speed=fan_speed, mode=preset_mode)
  File "/usr/local/lib/python3.12/site-packages/midealocal/devices/fa/__init__.py", line 335, in turn_on
    self.build_send(message)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 364, in build_send
    now = time.time(0.5)
          ^^^^^^^^^^^^^^
TypeError: time.time() takes no arguments (1 given)
```
```
无法执行动作“fan/turn_off” 。 time.time() takes no arguments (1 given)
```

**Comment by wuwentao** [comment]
@xiasi0 
你这是自己改过代码了，然后改错了……
请仔细看一下，是修改`time.sleep(0.5)`,而且是只修改这个0.5数字，其他都不变。
不是修改`now=time.time()` 而且也不是把中间加上0.5
我用提供的文件替换，或者基于这个文件修改。

**Comment by xiasi0** [comment]
好的，马上尝试重新修改

**Comment by xiasi0** [comment]
测试从0.5-2没有延迟明显改善。是否还需要增加数值？

**Comment by xiasi0** [comment]
1:03
1:33
1:30
设备已生效，实际同步到HA用时。这是三次测试。

**Comment by wuwentao** [comment]
@xiasi0 多谢反馈，那就是time.sleep(1)是否就行？降低到0.8或者0.5不行？

**Comment by xiasi0** [comment]
不是的，我测试0.5、0.8、1、1.5、2四个数值。均没有明显改善。

**Comment by wuwentao** [comment]
> 1:03 1:33 1:30 设备已生效，实际同步到HA用时。这是三次测试。

这个时间是什么意思？没看懂，是说30秒自动刷新了？

**Comment by xiasi0** [comment]
我点击开关后风扇立即打开，但是同步到HA实体需要等到1分钟后才会显示开启状态。

**Comment by wuwentao** [comment]
状态刷新默认是30秒自动刷新一次，如果超过30秒那不对，那就不正常了。

如果time.sleep(2)还不行，那还再看看其他办法。
时间太长不能这么干等，得用其他形式解决了，我再看看怎么修改吧。

**Comment by xiasi0** [comment]
好的。谢谢
#323 我看其他人也有类似情况。风扇部分我看在原来的仓库就有好多问题除了延迟情况没有，其它什么情况都有😂。

**Comment by xiasi0** [comment]
昨天添加不上去的柜机可以添加上去了。但是跟风扇一样存在延迟。

**Comment by xiasi0** [comment]
可以用discord了。买了一个月流量包

**Comment by xiasi0** [comment]
我这测试风扇类开关是没有延迟了。可以关闭了
