### ISSUE TITLE
Not working after migrating from georgezhao2010 version to 0.5.9.

### ISSUE THREAD

**Issue by goddade** [wuwentao/midea_ac_lan#322]
### HA版本

2024.9.2

### 集成版本

0.5.9

### 之前可正常使用的集成版本

0.3.22

### 设备类型及型号

 Air Conditioner 22396279 (0) 

### 使用的App

Homeassistant

### 问题详细描述

Not working after migrating from georgezhao2010 version to 0.5.9.

**Comment by chemelli74** [comment]
@goddadel just for a test and a internal reference, can you try downgrading to 0.5.7 ?
Thank you

**Comment by goddade** [comment]
> @goddade just for a test and a internal reference, can you try downgrading to 0.5.7 ? Thank you

Version 0.5.7 works well.

**Comment by goddade** [comment]
I tried 0.5.9 again, no luck.

**Comment by wuwentao** [comment]
> I tried 0.5.9 again, no luck.

@goddade 

we need debug log and error description to confirm the error.
if you always not provided  the error log and description the error detail, no one can understand it.

also not confirm it's a knonw issue or new issue.

please follow the issue template to report bug.

**Comment by wuwentao** [comment]
> @goddade just for a test and a internal reference, can you try downgrading to 0.5.7 ? Thank you

from 0.3.22 to 0.5.9......do you understand what's the bug ? and what's the error?

**Comment by goddade** [comment]
This is the log of version 0.5.7.
The microwave and water purifier are not working.

```
2024-09-26 00:26:33.467 DEBUG (微波炉) [midealocal.device] [211106238056629] Connection timed out
2024-09-26 00:26:33.470 DEBUG (微波炉) [midealocal.device] [211106238056629] Connecting to 192.168.1.166:6444
2024-09-26 00:26:36.553 DEBUG (微波炉) [midealocal.device] [211106238056629] Connection error
2024-09-26 00:26:36.555 DEBUG (微波炉) [midealocal.device] [211106238056629] Connecting to 192.168.1.166:6444
2024-09-26 00:26:39.625 DEBUG (微波炉) [midealocal.device] [211106238056629] Connection error
2024-09-26 00:26:39.626 DEBUG (微波炉) [midealocal.device] [211106238056629] Enabling device
2024-09-26 00:26:39.626 DEBUG (微波炉) [midealocal.device] [211106238056629] Status update: {'available': False}
2024-09-26 00:26:39.630 ERROR (微波炉) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
self.run()
File "/srv/homeassistant/lib/python3.12/site-packages/midealocal/device.py", line 515, in run
raise CannotConnect
midealocal.exceptions.CannotConnect
2024-09-26 00:26:45.533 ERROR (净水机) [midealocal.device] [186916977215679] Socket error - Connection closed by peer
2024-09-26 00:26:45.535 DEBUG (净水机) [midealocal.device] [186916977215679] Connecting to 192.168.1.170:6444
2024-09-26 00:26:45.538 DEBUG (净水机) [midealocal.device] [186916977215679] Connection error
2024-09-26 00:26:45.542 DEBUG (净水机) [midealocal.device] [186916977215679] Connecting to 192.168.1.170:6444
2024-09-26 00:26:45.545 DEBUG (净水机) [midealocal.device] [186916977215679] Connection error
2024-09-26 00:26:45.547 DEBUG (净水机) [midealocal.device] [186916977215679] Connecting to 192.168.1.170:6444
2024-09-26 00:26:45.578 DEBUG (净水机) [midealocal.device] [186916977215679] Connection error
2024-09-26 00:26:45.578 DEBUG (净水机) [midealocal.device] [186916977215679] Enabling device
2024-09-26 00:26:45.578 DEBUG (净水机) [midealocal.device] [186916977215679] Status update: {'available': False}
2024-09-26 00:26:45.583 ERROR (净水机) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
self.run()
File "/srv/homeassistant/lib/python3.12/site-packages/midealocal/device.py", line 515, in run
raise CannotConnect
midealocal.exceptions.CannotConnect
```

**Comment by goddade** [comment]
After I disabled and enabled the air conditioner, it worked again.
But version 0.5.7 does not require re enable.

**Comment by goddade** [comment]
After I disabled and enabled the air conditioner, it worked again.
But version 0.5.7 does not require re enable.

**Comment by goddade** [comment]
@
