### ISSUE TITLE
AC Unit not turning on

### ISSUE THREAD

**Issue by Ros-One** [wuwentao/midea_ac_lan#333]
### HA core version

2024.9.3

### Current integration version

v0.5.9

### Last known working integration version

v0.5.7

### Device type and model

Air Conditioner 00000Q1A (0) by Midea

### Working mobile app

NetHome Plus (iOS)

### The description of problem

I pick any mode (auto, heat, cool, dry, fan only) and the AC doesn't turn on.

### The logs

2024-09-25 11:12:01.820 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_ac_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-25 11:12:01.824 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-25 11:12:01.827 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-25 11:12:01.830 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration petkit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-25 11:12:03.184 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2024-09-25 11:12:03.220 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=46 from 2024-09-24 14:22:00.900975)
2024-09-25 11:12:17.021 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://alexa-api.nabucasa.com/access_token (400) 
2024-09-25 11:16:06.110 ERROR (MainThread) [homeassistant.components.xiaomi_ble] C4:7C:8D:66:E9:EF: Bluetooth error whilst polling: C4:7C:8D:66:E9:EF - C4:7C:8D:66:E9:EF: Failed to connect after 10 attempt(s): No backend with an available connection slot that can reach address C4:7C:8D:66:E9:EF was found: The proxy/adapter is out of connection slots or the device is no longer reachable; Add additional proxies (https://esphome.github.io/bluetooth-proxies/) near this device
2024-09-25 11:40:25.556 WARNING (MainThread) [zigpy.application] Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xEFF9)
2024-09-25 12:00:16.601 WARNING (MainThread) [homeassistant.components.light] light.lumi_lumi_light_aqcn02_light (<class 'homeassistant.components.zha.light.Light'>) set to unsupported color mode xy, expected one of {<ColorMode.COLOR_TEMP: 'color_temp'>}, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/home-assistant/core/issues?q=is:open+is%253Aissue+label%253A%2522integration%253A+zha%2522
2024-09-25 12:19:35.476 WARNING (MainThread) [homeassistant.components.automation.away_automation] Away Automation: Already running
2024-09-25 13:14:24.806 WARNING (MainThread) [homeassistant.components.light] light.lumi_lumi_light_aqcn02_light_3 (<class 'homeassistant.components.zha.light.Light'>) set to unsupported color mode xy, expected one of {<ColorMode.COLOR_TEMP: 'color_temp'>}, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/home-assistant/core/issues?q=is:open+is%253Aissue+label%253A%2522integration%253A+zha%2522
2024-09-25 13:14:24.808 WARNING (MainThread) [homeassistant.components.light] light.wardrobe_lights (<class 'homeassistant.components.group.light.LightGroup'>) set to unsupported color mode xy, expected one of {<ColorMode.COLOR_TEMP: 'color_temp'>}, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/home-assistant/core/issues?q=is:open+is%253Aissue+label%253A%2522integration%253A+group%2522
2024-09-25 13:14:24.818 WARNING (MainThread) [homeassistant.components.light] light.lumi_lumi_light_aqcn02_light_2 (<class 'homeassistant.components.zha.light.Light'>) set to unsupported color mode xy, expected one of {<ColorMode.COLOR_TEMP: 'color_temp'>}, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/home-assistant/core/issues?q=is:open+is%253Aissue+label%253A%2522integration%253A+zha%2522
2024-09-26 02:22:27.608 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.pirateweather_cloud_coverage_10h (<class 'custom_components.pirateweather.sensor.PirateWeatherSensor'>) took 0.801 seconds. Please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-09-26 07:35:23.374 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [546872325984] from fe80::1870:8af0:2f9e:4d2c (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15): Disconnected: Received close message during auth phase
2024-09-26 10:30:05.069 WARNING (MainThread) [homeassistant.components.automation.away_automation] Away Automation: Already running
2024-09-26 11:12:56.716 WARNING (MainThread) [homeassistant.components.homekit_controller.connection] HomeKit device update skipped as previous poll still in flight: 75:F8:FF:F2:2F:32
2024-09-26 11:15:46.861 ERROR (MainThread) [homeassistant.components.xiaomi_ble] C4:7C:8D:66:D8:24: Bluetooth error whilst polling: C4:7C:8D:66:D8:24 - C4:7C:8D:66:D8:24: Failed to connect after 8 attempt(s): TimeoutError
2024-09-27 11:12:55.632 WARNING (MainThread) [homeassistant.components.homekit_controller.connection] HomeKit device update skipped as previous poll still in flight: 75:F8:FF:F2:2F:32
2024-09-28 00:07:03.043 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.pirateweather_precip_probability_1h (<class 'custom_components.pirateweather.sensor.PirateWeatherSensor'>) took 0.888 seconds. Please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-09-28 09:53:29.566 ERROR (Bedroom) [midealocal.device] [31885837358285] send_message_v2 Unexpected socket error
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 284, in send_message_v2
    self._socket.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-09-28 09:53:31.389 ERROR (Kitchen) [midealocal.device] [18691697894915] send_message_v2 Unexpected socket error
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 284, in send_message_v2
    self._socket.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-09-28 11:12:54.861 WARNING (MainThread) [homeassistant.components.homekit_controller.connection] HomeKit device update skipped as previous poll still in flight: 75:F8:FF:F2:2F:32
2024-09-28 11:17:41.741 ERROR (MainThread) [homeassistant.components.xiaomi_ble] C4:7C:8D:66:D8:24: Bluetooth error whilst polling: C4:7C:8D:66:D8:24 - C4:7C:8D:66:D8:24: Failed to connect after 4 attempt(s): TimeoutError
2024-09-28 12:19:46.040 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://alexa-api.nabucasa.com/access_token (400) 
2024-09-28 12:25:04.443 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.pirateweather_ozone_0h (<class 'custom_components.pirateweather.sensor.PirateWeatherSensor'>) took 0.920 seconds. Please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-09-28 12:28:32.660 WARNING (MainThread) [homeassistant.components.automation.away_automation] Away Automation: Already running
2024-09-28 15:25:03.954 WARNING (MainThread) [homeassistant.components.automation.away_automation] Away Automation: Already running
2024-09-28 22:30:35.607 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.pirateweather_cloud_coverage_0h (<class 'custom_components.pirateweather.sensor.PirateWeatherSensor'>) took 0.930 seconds. Please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-09-29 08:29:06.668 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.pirateweather_precip_probability_0h (<class 'custom_components.pirateweather.sensor.PirateWeatherSensor'>) took 0.963 seconds. Please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
2024-09-29 09:08:16.906 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [546872037808] from 127.0.0.1 (Home Assistant/2024.9.1 (io.robbie.HomeAssistant; build:2024; iPadOS 18.0.0)): Disconnected: Did not receive auth message within 10 seconds
2024-09-29 11:12:55.731 WARNING (MainThread) [homeassistant.components.homekit_controller.connection] HomeKit device update skipped as previous poll still in flight: 75:F8:FF:F2:2F:32
2024-09-29 12:34:27.643 WARNING (MainThread) [homeassistant.components.automation.away_automation] Away Automation: Already running
2024-09-30 11:12:55.329 WARNING (MainThread) [homeassistant.components.homekit_controller.connection] HomeKit device update skipped as previous poll still in flight: 75:F8:FF:F2:2F:32
2024-09-30 11:19:14.631 ERROR (MainThread) [homeassistant.components.xiaomi_ble] C4:7C:8D:66:D8:24: Bluetooth error whilst polling: C4:7C:8D:66:D8:24 - C4:7C:8D:66:D8:24: Failed to connect after 4 attempt(s): failed to discover services, device disconnected
2024-09-30 15:11:09.789 DEBUG (Bedroom) [midealocal.device] [31885837358285] Sending: {'_device_type': <DeviceType.AC: 172>, '_message_type': <MessageType.query: 3>, '_body_type': <BodyType.X41: 65>, '_protocol_version': 0, '_message_id': 126, 'header': 'aa20ac00000000000003', 'body': '418100ff000000000000000000000000000000007e12', 'message_type': 'query', 'body_type': '41', 'self': <midealocal.devices.ac.message.MessageQuery object at 0x7f51b80cb0>}
2024-09-30 15:11:09.791 DEBUG (Bedroom) [midealocal.device] [31885837358285] Send failure, device socket is none, data: 8370008e2066304f6474f9fdbf046270523629295f1843d64bd2f6131bc33cf5a09df4666ae83a5c981c4ffe4ef43b5ac8996994054d3bc2369cafb7375c0041e9665f5738149d4caf0c7ff206003cc8692392abc30883852088f1939d1837a3a2a09e1d50a1dce33d7b08259089ef3ac88997a6ee7a5396e38ebdc25dca258aa487e78b749762f1c5761e1890dc00d0b1dc7f332a7c
2024-09-30 15:11:09.791 DEBUG (Bedroom) [midealocal.device] [31885837358285] _recv_message socket error, reconnect
2024-09-30 15:11:09.792 DEBUG (Bedroom) [midealocal.device] [31885837358285] refresh_status socket error, close and reconnect
2024-09-30 15:11:10.666 DEBUG (Bedroom) [midealocal.device] [31885837358285] Send failure, device socket is none, data: 8370005e2066c14a54f7aa55e68a4867a5439fffcb441d1855015f42ed2da140f02681175d3553f8d01490709bd5ee4f5b07f536edb073f7dd5cd57cd95ba73691ba7aef024e2c64c8d959c52a83511a214d50cceb07fe8f1e06b5b03594559fe43cf2649387
2024-09-30 15:11:10.666 DEBUG (Living Room) [midealocal.device] [18691697899803] Send failure, device socket is none, data: 8370005e206618b7571dd0d3365ff48309008d665e111292b29202ac91fd7265f713de6e01916bfed77b14cacb80381ea2d3034dbb6fef2a01021ddf0142c50d300bc8399a3705641a7b330f12cb5f4207433726e5bfe59b3edd4a50c63c0e9b958f4f32ff7a
2024-09-30 15:11:10.669 DEBUG (Kitchen) [midealocal.device] [18691697894915] Send failure, device socket is none, data: 8370005e2066f889c2130b2b749d83af04fd46cfd212f3cdb1d86cc46741411c4bd3d61fbdd208771a27bb3c6db989814c4550abb8aba2feef8c983e07ed2eff5d74cf8fd750bec495420a003cb3df28b483f960bf05326db698d78dc1c89f487462017e9fda
2024-09-30 15:11:14.799 DEBUG (Bedroom) [midealocal.device] [31885837358285] Send failure, device socket is none, data: 8370005e20661046770f399c969f1e80eebf052da0e2149b1166b6ab3ea87c64c5b37609093442e379d7cbd538074d0a11a74c94140e1769a7317de7d47e87dfff0c77cbfc1991d23025ca7840297af837e9b79a79966e8c78d17816cf6c06b3c6732e4ffbd6
2024-09-30 15:11:16.359 DEBUG (SyncWorker_46) [midealocal.device] [31885837358285] Sending: {'_device_type': <DeviceType.AC: 172>, '_message_type': <MessageType.set: 2>, '_body_type': 64, '_protocol_version': 0, '_message_id': 129, 'power': True, 'prompt_tone': False, 'mode': 5, 'target_temperature': 24.0, 'fan_speed': 102, 'swing_vertical': True, 'swing_horizontal': True, 'boost_mode': False, 'smart_eye': False, 'dry': False, 'aux_heating': False, 'eco_mode': False, 'temp_fahrenheit': False, 'sleep_mode': False, 'natural_wind': False, 'frost_protect': False, 'comfort_mode': True, 'header': 'aa23ac00000000000002', 'body': '4001a8660000003f00000000000000000000000000000181e7', 'message_type': 'set', 'body_type': '40', 'self': <midealocal.devices.ac.message.MessageGeneralSet object at 0x7f44d21130>}
2024-09-30 15:11:16.361 DEBUG (SyncWorker_46) [midealocal.device] [31885837358285] Send failure, device socket is none, data: 8370008e2066a530767ab932f99cd4e875239e8632bfb36dd2f655042cbecbe454dbda3e54c7242d52e06d51fa48ef3e917bd9e621cd4e432fee1e375785ed1ff15ecc13f903b821b6a98c83860cfc600f16fbd7e0d97a901339b0d2e4ed8cacbf22164d91051801068e29a2ca43ac6a0cd697f2756fedb511c95a682563f5baef50f785838149189fd91896d221187932db8dfd8fb0
2024-09-30 15:11:18.084 DEBUG (Kitchen) [midealocal.device] [18691697894915] Send failure, device socket is none, data: 8370005e2066856b19963e05696d657321a1233f7930df2498b555af78e7487875a77c63fdafbfe4f51edbbeb564602cc25307976923a1d374c9c7661dbd583dbf729044a665f1c25ca56b2a657915ac7e3c7bcb722b92e786683d19b350bc08dc296a539776
2024-09-30 15:11:19.853 DEBUG (SyncWorker_22) [midealocal.device] [31885837358285] Sending: {'_device_type': <DeviceType.AC: 172>, '_message_type': <MessageType.set: 2>, '_body_type': 64, '_protocol_version': 0, '_message_id': 130, 'power': True, 'prompt_tone': False, 'mode': 3, 'target_temperature': 24.0, 'fan_speed': 102, 'swing_vertical': True, 'swing_horizontal': True, 'boost_mode': False, 'smart_eye': False, 'dry': False, 'aux_heating': False, 'eco_mode': False, 'temp_fahrenheit': False, 'sleep_mode': False, 'natural_wind': False, 'frost_protect': False, 'comfort_mode': True, 'header': 'aa23ac00000000000002', 'body': '400168660000003f00000000000000000000000000000182c6', 'message_type': 'set', 'body_type': '40', 'self': <midealocal.devices.ac.message.MessageGeneralSet object at 0x7f416d6420>}
2024-09-30 15:11:19.855 DEBUG (SyncWorker_22) [midealocal.device] [31885837358285] Send failure, device socket is none, data: 8370008e2066df798c59dff1dece938615113b977497ca5708079cb31c3d76a16595090378748ae08de0b1be711c47020b9f87e8f1e66eb33406d858b294f9244ca859b2fc5dbb0f2bb365f037c43e6e813682dbcecc7c056bf00baf85f425827ee16995b09041be059e92da98a67fcdc5f3198f279d6b054365375e4ffb01c53a4d4bd0f0921da2ff95e26cbb3d7b3dfd4ce25da2b5
2024-09-30 15:11:20.684 DEBUG (Kitchen) [midealocal.device] [18691697894915] Send failure, device socket is none, data: 8370005e2066e047bd818aa6350e24ebf104db39fb2be0d3f44b58d3f93ffbf48477bb076029e654dc424dfe51e3e889c43521f222117c993359fa501069eec6ff7aee4a9f60ddfd66641b1ffc0c46290b72d50092fbf5a94a362abe2f73c6237dfba93e90b0
2024-09-30 15:11:20.685 DEBUG (Living Room) [midealocal.device] [18691697899803] Send failure, device socket is none, data: 8370005e20663b8c3881053ccf51714b0cb800fa398e3d5c807fd69a5a0230c0f4de4df2d585146f5123e1468c5cf15d8e32b70c57065edb938b49bd06407832667b49c70a3527aac17604910fe378a98644d7317e39315a06320601bd3c25b7d9910bafca9a
2024-09-30 15:11:20.686 DEBUG (Bedroom) [midealocal.device] [31885837358285] Send failure, device socket is none, data: 8370005e2066675ea7a3436e80ef204c737065468bc355f081fe37182e0f23c8c2e0afbc0002e4819e36ce334401cb86518d7b078580f1cc434daa53d3ed8e2665a0d061cabf162b2e9d8daf4a98bc301f360a63b35c132534e5fcb7390a815798f5c877ebb7
2024-09-30 15:11:23.574 DEBUG (SyncWorker_10) [midealocal.device] [31885837358285] Sending: {'_device_type': <DeviceType.AC: 172>, '_message_type': <MessageType.set: 2>, '_body_type': 64, '_protocol_version': 0, '_message_id': 131, 'power': True, 'prompt_tone': False, 'mode': 2, 'target_temperature': 24.0, 'fan_speed': 102, 'swing_vertical': True, 'swing_horizontal': True, 'boost_mode': False, 'smart_eye': False, 'dry': False, 'aux_heating': False, 'eco_mode': False, 'temp_fahrenheit': False, 'sleep_mode': False, 'natural_wind': False, 'frost_protect': False, 'comfort_mode': True, 'header': 'aa23ac00000000000002', 'body': '400148660000003f00000000000000000000000000000183c3', 'message_type': 'set', 'body_type': '40', 'self': <midealocal.devices.ac.message.MessageGeneralSet object at 0x7f419c7da0>}
2024-09-30 15:11:23.576 DEBUG (SyncWorker_10) [midealocal.device] [31885837358285] Send failure, device socket is none, data: 8370008e2066bdd73965774f0c471d613bce7a10fb48fa154f8284dc71c10c2f134dcf33809c108197532166a166d4768edb02318b838d203e627911093d18c029bdd34b7a8ac58373c5cc20efcab7876b8828019cf177babf48742a056faff5280028da1aa45396eb302c37311b4eb22d38f830240ee8e10b28e5809a269c637795e1325e9da2f407551aae395693af17089891f59d
2024-09-30 15:11:24.816 DEBUG (Bedroom) [midealocal.device] [31885837358285] Send failure, device socket is none, data: 8370005e2066febfae37130958b0ca4b4a88958625b70a94c048ac0fad4debc1e1aeec9c89f41573992109c291c6edccb3105467ff5125ee3d81d864a3940c5100fd1580986891b6663b591ce5c67dce47648e07959e2fe90cd60ba9b1320ccaf1a856fc5c01
2024-09-30 15:11:27.130 DEBUG (SyncWorker_6) [midealocal.device] [31885837358285] Sending: {'_device_type': <DeviceType.AC: 172>, '_message_type': <MessageType.set: 2>, '_body_type': 64, '_protocol_version': 0, '_message_id': 132, 'power': True, 'prompt_tone': False, 'mode': 4, 'target_temperature': 24.0, 'fan_speed': 102, 'swing_vertical': True, 'swing_horizontal': True, 'boost_mode': False, 'smart_eye': False, 'dry': False, 'aux_heating': False, 'eco_mode': False, 'temp_fahrenheit': False, 'sleep_mode': False, 'natural_wind': False, 'frost_protect': False, 'comfort_mode': True, 'header': 'aa23ac00000000000002', 'body': '400188660000003f0000000000000000000000000000018483', 'message_type': 'set', 'body_type': '40', 'self': <midealocal.devices.ac.message.MessageGeneralSet object at 0x7f761deb40>}
2024-09-30 15:11:27.132 DEBUG (SyncWorker_6) [midealocal.device] [31885837358285] Send failure, device socket is none, data: 8370008e20667fdad999ef9b3c7744b44564b0423fcabe4ac7b2c152973af2a2c33f78a1d5088cbf8fd70a85b92373987d31027ff108fff675ef9c0ccacd0650df4ad2d253d3dc95cb8002f6677da338ed530c3c16449e8b80b87ed20245ad96afea344a25cba054d4fba81e73ec7f28a3dbaca34dd8572d1453771c38a3dd74ad9b83e4146544c7026caddac8a2ed1b07c7fda7261d
2024-09-30 15:11:28.097 DEBUG (Kitchen) [midealocal.device] [18691697894915] Send failure, device socket is none, data: 8370005e20662c43f466998900d800d2463b0e0e8653cc881f2edc8b8dcc177917319aa90d1ab12c0fb70229c7c21dfb79ff71c5400222236b7d0f47e793444b9ad8efe0bdbf63a11f578c1cbc6281c763923b03cc5d411715266e4ccca23096b6865f67632c
2024-09-30 15:11:30.281 DEBUG (SyncWorker_62) [midealocal.device] [31885837358285] Sending: {'_device_type': <DeviceType.AC: 172>, '_message_type': <MessageType.set: 2>, '_body_type': 64, '_protocol_version': 0, '_message_id': 133, 'power': True, 'prompt_tone': False, 'mode': 1, 'target_temperature': 24.0, 'fan_speed': 102, 'swing_vertical': True, 'swing_horizontal': True, 'boost_mode': False, 'smart_eye': False, 'dry': False, 'aux_heating': False, 'eco_mode': False, 'temp_fahrenheit': False, 'sleep_mode': False, 'natural_wind': False, 'frost_protect': False, 'comfort_mode': True, 'header': 'aa23ac00000000000002', 'body': '400128660000003f00000000000000000000000000000185f3', 'message_type': 'set', 'body_type': '40', 'self': <midealocal.devices.ac.message.MessageGeneralSet object at 0x7f4172d220>}
2024-09-30 15:11:30.283 DEBUG (SyncWorker_62) [midealocal.device] [31885837358285] Send failure, device socket is none, data: 8370008e20663f94ed987ac531aff90f5efb3773b4de9380f7409d87eda80cda8944badea0946793ad9a70fde3df760d375c0a856f145fff670b5fced6c535332bb3bf485d3152a6c2816459dd2499b58deb8cca67a5473bb8e98845a1a0454accf1054f03186bb9a1b2abb7130f03f373e4f38aac5d2b55b09c2de50b022b0f524f7cf4a624aaa5ca45a905ecfd698aace7a6db4b0e
2024-09-30 15:11:30.699 DEBUG (Bedroom) [midealocal.device] [31885837358285] Send failure, device socket is none, data: 8370005e2066373890f1e6b892eefed2871c8f2a7c18ca2deca65717fa5506a7d498943fc82e02643a97aad9b540bce8e815c1e0a143cf14498d18199c57ced0bffd7571d220fbe2687dd61d918ac6d47a49d2374556569fea3f8333dc9ab594e50ae3d90496
2024-09-30 15:11:30.699 DEBUG (Kitchen) [midealocal.device] [18691697894915] Send failure, device socket is none, data: 8370005e2066d4560af1026b0d515c5b0577e3becf7caffa501c06fa909f77370c41f533ff3f0b367e4785a3af1328b9db62e91d8efd43b679a216d2e8bde4761de6fec2ddcfe1763a997fc50d94a953ba287d14673aa684364845e3a21a0adf23ddf5c3c4a5
2024-09-30 15:11:30.701 DEBUG (Living Room) [midealocal.device] [18691697899803] Send failure, device socket is none, data: 8370005e2066e7bb22b3579e045f545772fc8c04a29c19d7dfb533862dd98b51f777fb91a5e8e5b7c27315195d535814a5ff22b777a19f43fc1b528f82290f8e16081084b647b4adfce7af58a60059cf7889eff173513a07692c9d41c2c8859f67955be4c2f0
2024-09-30 15:11:32.502 DEBUG (Bedroom) [midealocal.device] [31885837358285] Sending: {'_device_type': <DeviceType.AC: 172>, '_message_type': <MessageType.query: 3>, '_body_type': <BodyType.X41: 65>, '_protocol_version': 0, '_message_id': 134, 'header': 'aa20ac00000000000003', 'body': '418100ff0000000000000000000000000000000086a4', 'message_type': 'query', 'body_type': '41', 'self': <midealocal.devices.ac.message.MessageQuery object at 0x7f4170bec0>}
2024-09-30 15:11:32.504 DEBUG (Bedroom) [midealocal.device] [31885837358285] Send failure, device socket is none, data: 8370008e206636ca7f8a56e9a7723db4bf50ad90ae945164a9f685847ab385c150a39c7a8028426b5068956e7b4f98b00ad0690605eadd632a77047d42a64323e4a842b20d70a75b3689ff4e755e16667a7abb4a261b393d3b89bb3501e5bf4032744a3f9ea1f5e4225f419c81b2d45caae59d17d586c17b561c8ee74b9d775b869be5bb6217a66adf8d6a43f76fd3d6e2ccb44c5140
2024-09-30 15:11:32.504 DEBUG (Bedroom) [midealocal.device] [31885837358285] _recv_message socket error, reconnect
2024-09-30 15:11:32.504 DEBUG (Bedroom) [midealocal.device] [31885837358285] refresh_status socket error, close and reconnect
2024-09-30 15:11:33.406 DEBUG (Kitchen) [midealocal.device] [18691697894915] Sending: {'_device_type': <DeviceType.AC: 172>, '_message_type': <MessageType.query: 3>, '_body_type': <BodyType.X41: 65>, '_protocol_version': 0, '_message_id': 137, 'header': 'aa20ac00000000000003', 'body': '418100ff0000000000000000000000000000000089e5', 'message_type': 'query', 'body_type': '41', 'self': <midealocal.devices.ac.message.MessageQuery object at 0x7f53ed34a0>}
2024-09-30 15:11:33.408 DEBUG (Kitchen) [midealocal.device] [18691697894915] Send failure, device socket is none, data: 8370008e2066905537b6b2f171ca3526280a6092a86e9ea9e3aa7bfeb6db1498ee776b9ef048675ba047f6932738f12c37f591fc26cdc423ab1afe2438f0953d9d7d4c7e96e12218349b658e138c69acfad1b5e60c1397ec1c19463d72d98ff05608c3fc059c615da122d9710542c6c1293d49dbf0354248eec0012f0097b821962a04ebb142c12653011a553ff3910c09c7767a495e
2024-09-30 15:11:33.409 DEBUG (Kitchen) [midealocal.device] [18691697894915] _recv_message socket error, reconnect
2024-09-30 15:11:33.409 DEBUG (Kitchen) [midealocal.device] [18691697894915] refresh_status socket error, close and reconnect
2024-09-30 15:11:34.832 DEBUG (Bedroom) [midealocal.device] [31885837358285] Send failure, device socket is none, data: 8370005e2066f6575dc33526d89675e0c451b9dc85cf64619b7f380224f13c480916c7bdd4b179a24e14c0cb18089633d1b0a4bca5cb185ad2f92dca9e69183a3aeff519fbcc1a8a7dae6a93215a872f4ecacaefbfe4d83fc7a4f6c51134a9bdb8c9a8425723

**Comment by wuwentao** [comment]
thanks for your bug report.
it should be fix in latest v0.6.0, once it publish, this PR will be close, please have a try.
if it still can't work for you, please update the latest result with debug log info
