### ISSUE TITLE
空调、热水器新版无法控制，反馈温度也错误。

### ISSUE THREAD

**Issue by scegg** [wuwentao/midea_ac_lan#340]
### HA版本

2024.10.0

### 集成版本

0.6.0

### 之前可正常使用的集成版本

0.5.9

### 设备类型及型号

Air Conditioner 22251637 (32773) by Midea

### 使用的App

美的美居

### 问题详细描述

制冷会正常开始，但只要修改温度就会立即关机。报告的当前室温也不正确（21，美的美居app报告为25）。

另，还有一个热水器“Gas Water Heater 5110188D (252) by Midea”也是报告了错误的水温（50，美的美居报告29）和设置温度无效。

0.5.9版本没有问题。回滚倒0.5.9问题都可以解决。

### The logs

HA用的是web版，README中的步骤做不到。

**Comment by BH4WHN** [comment]
0.60遇到类似问题，型号：MDV Wi-Fi Controller 00000M33 (0) Wifi线控器可以开机无法关机，界面始终显示空调关闭，预设功能失灵（如eco和睡眠）；温度调节没有了0.5度步进但可整数修改，当前温度不显示，只显示设定温度。之前0.59正常，但开机后ha界面反馈迟缓，点了开机后10秒ha里才显示开机。

**Comment by Live2000** [comment]
我这边也出现了，0.5.9的时候，空调状态长时间不更新，更新0.6.0以后，空调的温度传感器、湿度传感器、功率传感器那些都无法获取数据，全部变成“未知”

日志记录器: midealocal.device
来源: /usr/local/lib/python3.12/site-packages/midealocal/device.py:434
首次出现: 18:04:09 (173 次总计出现)
上次记录: 18:10:48

[208907216782077] Error in process message, msg = aa2aac00000000000803c000ab667f7f00000008006aff0f00030000000000000000000000000dff853a02
[208907216782077] Error in process message, msg = aa28ac00000000000803b106420000010118000000150000001700000164330200004b00000085bcbc
[208907216782077] Error in process message, msg = aa20ac00000000000803c1210144000026570000000000000000000030000176de
[208907216726897] Error in process message, msg = aa2aac000000000008a000ac0500162911183d30111821303d11303d3d0d14213d11110002000000017d69
[208907216726897] Error in process message, msg = aa2aac00000000000803c0002b657f7f00000000006aff0f000000000000000000000000000090ff88e85a
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 423, in parse_message
    cont = self.pre_process_message(decrypted)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 389, in pre_process_message
    message = MessageApplianceResponse(msg)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midealocal/message.py", line 613, in __init__
    super().__init__(message)
  File "/usr/local/lib/python3.12/site-packages/midealocal/message.py", line 579, in __init__
    self.protocol_version = ProtocolVersion(self._header[-2])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 8 is not a valid ProtocolVersion

**Comment by chemelli74** [comment]
We have identified the issue and we are working on a solution.
Probably later today we will release a new version.

In the mean time, can you be so kind to share the device info ?
You can collect them via: `midea-local download -sn <serial>`
