### ISSUE TITLE
163 is not a valid BodyType

### ISSUE THREAD

**Issue by Rihan9** [wuwentao/midea_ac_lan#341]
### HA core version

2024.09

### Current integration version

0.6.0

### Last known working integration version

0.5.9

### Device type and model

Air Conditioner 00000Q1B (0)

### Working mobile app

SmartHome

### The description of problem

Hi,
I have the following error log related to your integration:
```
[152832116408439] Error in process message, msg = aa2bac00000000000204a300000000000000000000000000000000000000000000000000000000000001bcc3
[152832116408439] Error in process message, msg = aa2bac00000000000204a500001e00000000ec0100000000000005007d00000000645e16000000000001dd3b
[152832116408439] Error in process message, msg = aa2bac00000000000204a600000000000000000000000000000000000000000000000000000000000001fb81
[152832116408439] Error in process message, msg = aa2bac00000000000204a200000000000000000000000000000000000000000000000000000000000001fa86
[152832116297355] Error in process message, msg = aa40e200000000000004010100002c500004000000370000170000000f00000000000000003c0000000000000000000000010000000000000000000000000000be
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 425, in parse_message
    status = self.process_message(bytes(decrypted))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midealocal/devices/ac/__init__.py", line 190, in process_message
    message = MessageACResponse(bytearray(msg), self._power_analysis_method)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midealocal/devices/ac/message.py", line 910, in __init__
    super().__init__(message)
  File "/usr/local/lib/python3.12/site-packages/midealocal/message.py", line 584, in __init__
    self.body_type = self._body.body_type
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midealocal/message.py", line 509, in body_type
    return BodyType(self._data[0])
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 163 is not a valid BodyType
```

for now, I don't see any problems with my devices, but I'll keep an eye on them and do some tests since I'm not using them at the moment.

**Comment by chemelli74** [comment]
closed via #343
