### ISSUE TITLE
colmo管线机da01无法显示tds等传感器状态

### ISSUE THREAD

**Issue by leqiyufeng** [wuwentao/midea_ac_lan#428]
### HA版本

2024.12.5

### 集成版本

0.6.5

### 之前可正常使用的集成版本

0

### 设备类型及型号

Water Drinking Appliance 6320084C (707)

### 使用的App

美的美居

### 问题/Bug详细描述

1. colmo管线机、da01
2. 传感器信息无法显示，入tds进水，tds出水（我比较关注），唯一能显示总耗水量，并且管线机无电源开关(设备匹配上因该不对)
3. 美的美居控制正常

### The logs

附件：
[home-assistant_midea_ac_lan_2024-12-24T05-02-14.956Z.log](https://github.com/user-attachments/files/18235988/home-assistant_midea_ac_lan_2024-12-24T05-02-14.956Z.log)

日志记录器: homeassistant.config_entries
来源: config_entries.py:855
首次出现: 13:02:10 (1 次总计出现)
上次记录: 13:02:10

Error unloading entry Colmo管线机 for midea_ac_lan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 855, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/__init__.py", line 276, in async_unload_entry
    dm.close()
    ~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/midealocal/device.py", line 542, in close
    self.close_socket()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/midealocal/device.py", line 551, in close_socket
    self._socket.close()
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by wuwentao** [comment]
@leqiyufeng 
提供的debug log没有意义，显示设备断开连接了，请尝试重启DA01设备，重启HA，应该可以恢复正常。
```
2024-12-24 13:02:10.177 DEBUG (Colmo管线机) [midealocal.device] [178120884692271] Connection reset by peer
2024-12-24 13:02:10.177 DEBUG (Colmo管线机) [midealocal.device] [178120884692271] Socket closed
2024-12-24 13:02:10.177 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Colmo管线机 for midea_ac_lan
```

其次，关于你说的无法显示tds传感器状态，请问一下，你的DA01，在美居app是否可以显示这些数据？
如果没猜错的话，colmo DA01的app应该是根本不支持这些功能的，也就是设备压根没有这些传感器设备，那又怎么可能可以显示呢？
设备自身硬件不支持，巧妇难为无米之炊。

**Comment by leqiyufeng** [comment]
@wuwentao 
明白了，你说的很对，是设备自身问题没有提供更细的传感器信息。非常感谢！
