### ISSUE TITLE
v0.4.1版本日志报错，导致日志文件大小急剧增加

### ISSUE THREAD

**Issue by lyfqdl** [wuwentao/midea_ac_lan#63]
### HA版本

2024.5.3

### 集成版本

v0.4.1

### 设备类型及型号

AIR

### 使用的App

美的美居

### 问题详细描述

v0.4.1版本日志报错，导致home-assistant.log日志文件大小急剧增加，占满磁盘空间。

### The logs

日志: homeassistant
来源: helpers/entity.py:1665
首次发生: 2024年6月3日 下午11:37:28 (20988 全部发生)
上次记录: 上午8:17:08

Error doing job: Exception in callback Entity._async_write_ha_state_from_call_soon_threadsafe()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1001, in _async_write_ha_state_from_call_soon_threadsafe
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1015, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
    return self.state == STATE_ON
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1665, in state
    if (is_on := self.is_on) is None:

                 ^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

**Comment by wuwentao** [comment]
抱歉修改代码规范产生了如此严重的问题，也非常感谢反馈bug，查了一下修改历史，这个问题应该是最近在使用mypy进行标准化所有python源码格式，数据类型，修改fan.py文件后出现了一些bug。

从文件报错的地方看：
```
File "/config/custom_components/midea_ac_lan/fan.py", line 159, in is_on
return self.state == STATE_ON
````
我简单进行了一下修改，您是否可以手工替换修改后的fan.py文件，测试一下？

或者单独ssh登录运行home assiant的机器，手工修改`/config/custom_components/midea_ac_lan/fan.py`第159行，再进行测试也行。
估计也需要您先清空日志文件，如有问题可随时沟通，或者首页readme加入Discord 软件在线沟通。

修改的PR diff在这里查看：
https://github.com/wuwentao/midea_ac_lan/pull/65/files

主要就是将fan.py文件中第159行的：
`return self.state == STATE_ON`
修改为:
`return cast(bool, self._device.get_attribute(ACAttributes.fresh_air_power))`

**Comment by lyfqdl** [comment]
非常感谢这么快修复问题，已验证问题解决。

**Comment by wuwentao** [comment]
> 非常感谢这么快修复问题，已验证问题解决。

收到，多谢确认！
