### ISSUE TITLE
洗衣机状态不更新

### ISSUE THREAD

**Issue by flamestsui** [wuwentao/midea_ac_lan#85]
### HA版本

2024.6.2

### 集成版本

0.4.1

### 设备类型及型号

Top Load Washer 38019361 (27700)

### 使用的App

美的美居

### 问题详细描述

我在app开启后，HA上状态不会同步，必须要重载状态才会更新，而且，在HA点击也没用

![Snipaste_2024-06-14_17-32-36](https://github.com/wuwentao/midea_ac_lan/assets/3983453/ad52a997-6580-4336-a6a9-2b553f380ed3)
![Snipaste_2024-06-14_17-32-04](https://github.com/wuwentao/midea_ac_lan/assets/3983453/a9c3491f-4c64-4ff8-a316-d89dca9e74c2)

**Comment by wuwentao** [comment]
@flamestsui 大概找到可能的问题所在，请问是否方便debug，可能需要直接修改源码去验证是否能够解决问题？
需要修改homeassiant core里面安装的midealocal这个python库来确认。

如果不方便的话，就等一段时间，随后我直接提交修改，下个版本解决吧。

**Comment by flamestsui** [comment]
@wuwentao 
2024-06-16 09:01:58.181 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000004040100000000f300ff0f62f1000000ff003200ffffffffff007a
2024-06-16 09:02:00.279 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030100000000f300ff0f62f1000000ff003200ffda346c6d0091
2024-06-16 09:02:04.465 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000002020100000000f300ff0f62f1000000ff003200ffffffffff007e
2024-06-16 09:02:10.471 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Unknown error :/usr/local/lib/python3.12/site-packages/midealocal/device.py, 374, AttributeError("'NoneType' object has no attribute 'recv'")
2024-06-16 09:02:11.066 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030100000000f300ff0f62f1000000ff003200ffda346c6d0091
2024-06-16 09:02:18.251 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000002020100000000f300ff0f62f1000000ff003200ffffffffff007e
2024-06-16 09:02:24.281 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Unknown error :/usr/local/lib/python3.12/site-packages/midealocal/device.py, 374, AttributeError("'NoneType' object has no attribute 'recv'")
2024-06-16 09:02:24.330 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030100000000f300ff0f62f1000000ff003200ffda346c6d0091
2024-06-16 09:02:28.342 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000004040000000000f300ff0f62f1000000ff003200ffffffffff007b
2024-06-16 09:02:29.245 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000004040000000000f300ff0f62f1000000ff003200ffffffffff007b
2024-06-16 09:02:32.248 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Unknown error :/usr/local/lib/python3.12/site-packages/midealocal/device.py, 374, AttributeError("'NoneType' object has no attribute 'recv'")
2024-06-16 09:02:33.021 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030000000000f300ff0f62f1000000ff003200ffda346c6d0092

**Comment by flamestsui** [comment]
2024-06-16 09:01:58.181我用美居打开开关，不刷新，重载才刷新

**Comment by wuwentao** [comment]
@flamestsui 

我本地的设备也有一个RefreshFailed()的错误，不过看你这个错误，好像和我本地的还不一样，设备不同。

先把midealocal的debug log也加上吧，在`configuration.yaml`中，参考如下，最后二行：
```
logger:
  default: warn
  logs:
    custom_components.midea_ac_lan: debug
    midealocal: debug
```

**Comment by flamestsui** [comment]
@wuwentao 
2024-06-17 09:01:56.526 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Connecting to 192.168.88.206:6444
2024-06-17 09:01:56.564 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Connected
2024-06-17 09:01:56.564 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Authentication success
2024-06-17 09:01:56.564 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa1dda000000000000a0', 'body': '00000000000000000000000000000000000000', 'message type': 'a0', 'body type': 'None'}
2024-06-17 09:01:57.116 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Received: {'header': 'aa2ada000000000000a0', 'body': '00da346c00000000000000000000000000000000000000000000000000000000', 'message type': 'a0', 'body type': '00'}
2024-06-17 09:01:57.116 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Device protocol version: 0
2024-06-17 09:01:57.117 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '03', 'body type': '03'}
2024-06-17 09:01:57.312 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030000000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '03', 'body type': '03'}
2024-06-17 09:01:57.312 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030000000000f300ff0f62f1000000ff003200ffda346c6d0092
2024-06-17 09:01:57.312 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Status update: {'available': True}

2024-06-17 09:02:27.410 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '03', 'body type': '03'}
2024-06-17 09:02:27.533 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030000000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '03', 'body type': '03'}
2024-06-17 09:02:27.533 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030000000000f300ff0f62f1000000ff003200ffda346c6d0092
2024-06-17 09:02:57.598 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '03', 'body type': '03'}
2024-06-17 09:02:57.689 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030000000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '03', 'body type': '03'}
2024-06-17 09:02:57.689 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030000000000f300ff0f62f1000000ff003200ffda346c6d0092
2024-06-17 09:03:27.796 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '03', 'body type': '03'}
2024-06-17 09:03:27.925 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030000000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '03', 'body type': '03'}
2024-06-17 09:03:27.925 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030000000000f300ff0f62f1000000ff003200ffda346c6d0092
2024-06-17 09:03:57.993 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '03', 'body type': '03'}
2024-06-17 09:03:58.080 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030000000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '03', 'body type': '03'}
2024-06-17 09:03:58.080 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030000000000f300ff0f62f1000000ff003200ffda346c6d0092
2024-06-17 09:04:28.138 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '03', 'body type': '03'}
2024-06-17 09:04:28.223 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030000000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '03', 'body type': '03'}
2024-06-17 09:04:28.224 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030000000000f300ff0f62f1000000ff003200ffda346c6d0092
2024-06-17 09:04:58.291 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '03', 'body type': '03'}
2024-06-17 09:04:58.462 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030000000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '03', 'body type': '03'}
2024-06-17 09:04:58.462 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030000000000f300ff0f62f1000000ff003200ffda346c6d0092
2024-06-17 09:05:28.563 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '03', 'body type': '03'}
2024-06-17 09:05:28.714 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030000000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '03', 'body type': '03'}
2024-06-17 09:05:28.714 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030000000000f300ff0f62f1000000ff003200ffda346c6d0092
2024-06-17 09:05:58.766 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '03', 'body type': '03'}
2024-06-17 09:05:58.856 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030000000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '03', 'body type': '03'}
2024-06-17 09:05:58.856 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030000000000f300ff0f62f1000000ff003200ffda346c6d0092

2024-06-17 09:07:29.211 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '03', 'body type': '03'}
2024-06-17 09:07:29.386 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030100000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '03', 'body type': '03'}
2024-06-17 09:07:29.386 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030100000000f300ff0f62f1000000ff003200ffda346c6d0091
2024-06-17 09:07:29.589 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000004', 'body': '040100000000f300ff0f62f1000000ff003200ffffffffff00', 'message type': '04', 'body type': '04'}
2024-06-17 09:07:29.589 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000004040100000000f300ff0f62f1000000ff003200ffffffffff007a
2024-06-17 09:07:35.301 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Connecting to 192.168.88.206:6444
2024-06-17 09:07:35.303 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Connected
2024-06-17 09:07:35.303 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Authentication success
2024-06-17 09:07:35.304 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa1dda000000000000a0', 'body': '00000000000000000000000000000000000000', 'message type': 'a0', 'body type': 'None'}
2024-06-17 09:07:35.792 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Received: {'header': 'aa2ada000000000000a0', 'body': '00da346c00000000000000000000000000000000000000000000000000000000', 'message type': 'a0', 'body type': '00'}
2024-06-17 09:07:35.792 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Device protocol version: 0
2024-06-17 09:07:35.792 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '03', 'body type': '03'}
2024-06-17 09:07:35.986 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030100000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '03', 'body type': '03'}
2024-06-17 09:07:35.986 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030100000000f300ff0f62f1000000ff003200ffda346c6d0091
2024-06-17 09:07:35.987 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Status update: {'available': True}
2024-06-17 09:07:53.171 DEBUG (SyncWorker_9) [midealocal.device] [140737488443965] Sending: {'header': 'aa0dda00000000000002', 'body': '0200ff', 'message type': '02', 'body type': '02'}
2024-06-17 09:07:53.347 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000002', 'body': '020100000000f300ff0f62f1000000ff003200ffffffffff00', 'message type': '02', 'body type': '02'}
2024-06-17 09:07:53.347 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000002020100000000f300ff0f62f1000000ff003200ffffffffff007e

2024-06-17 09:08:03.230 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000004', 'body': '040000000000f300ff0f62f1000000ff003200ffffffffff00', 'message type': '04', 'body type': '04'}
2024-06-17 09:08:03.230 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000004040000000000f300ff0f62f1000000ff003200ffffffffff007b
2024-06-17 09:08:06.234 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '03', 'body type': '03'}
2024-06-17 09:08:06.328 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030000000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '03', 'body type': '03'}
2024-06-17 09:08:06.328 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030000000000f300ff0f62f1000000ff003200ffda346c6d0092
2024-06-17 09:08:07.144 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Connecting to 192.168.88.206:6444
2024-06-17 09:08:07.152 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Connected
2024-06-17 09:08:07.152 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Authentication success
2024-06-17 09:08:07.152 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa1dda000000000000a0', 'body': '00000000000000000000000000000000000000', 'message type': 'a0', 'body type': 'None'}
2024-06-17 09:08:07.330 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Send failure, device disconnected, data: 5a5a011038007b000000000021070809110618143d5a01000080000000000000000000000000000067a26fd4be6101483cafcd19fca0a1dd
2024-06-17 09:08:07.330 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Unknown error :/usr/local/lib/python3.12/site-packages/midealocal/device.py, 374, AttributeError("'NoneType' object has no attribute 'recv'")
2024-06-17 09:08:07.534 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Received: {'header': 'aa2ada000000000000a0', 'body': '00da346c00000000000000000000000000000000000000000000000000000000', 'message type': 'a0', 'body type': '00'}
2024-06-17 09:08:07.534 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Device protocol version: 0
2024-06-17 09:08:07.534 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '03', 'body type': '03'}
2024-06-17 09:08:07.721 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030000000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '03', 'body type': '03'}
2024-06-17 09:08:07.721 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030000000000f300ff0f62f1000000ff003200ffda346c6d0092
2024-06-17 09:08:07.721 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Status update: {'available': True}

**Comment by wuwentao** [comment]
今天暂时还顾不上看，有点别的事情要。
不过我本地的冰箱也出现过一个类似的错误，先贴上log，后续再来看细节方面吧。
你的版本如果使用的是v0.4.1,那应该安装的是midea-local v1.0.3
我这边使用的是v1.0.5测试版本，我这里的错误log信息：

```
2024-06-17 07:52:25.708 DEBUG (多开门冰箱) [midealocal.device] [178120884631450] Sending: {'header': 'aa0aca00000000000003', 'body': '', 'message type': '03', 'body type': 'None'}
2024-06-17 07:52:25.965 ERROR (多开门冰箱) [midealocal.device] [178120884631450] Error in process message, msg = aa12cad8000000000003010000000000000048
2024-06-17 07:52:26.909 DEBUG (管线机) [midealocal.devices.ed] [210006727698088] Received: {'header': 'aa89ed00000000000004', 'body': 'ff010700400810010201100002400103010103101e05103706102d0b10531150d01500000012500000000000203000000021505f000000002250000000000023600f1e32000000264000001e00272000002810002910003070000000000000003110003620780037300000000522d20007121e08121f09121f3a4000000000', 'message type': '04', 'body type': 'ff'}
2024-06-17 07:52:26.909 DEBUG (管线机) [midealocal.device] [210006727698088] Status update: {'power': False, 'water_consumption': 5.584, 'child_lock': True}
```

```
Logger: midealocal.device
Source: /usr/local/lib/python3.12/site-packages/midealocal/device.py:296
First occurred: 7:52:25 AM (1 occurrences)
Last logged: 7:52:25 AM

[178120884631450] Error in process message, msg = aa12cad8000000000003010000000000000048
```

除此之外，还有一个refresh failed的错误：
```
Logger: midealocal.device
Source: /usr/local/lib/python3.12/site-packages/midealocal/device.py:444
First occurred: June 16, 2024 at 11:53:01 PM (1 occurrences)
Last logged: June 16, 2024 at 11:53:01 PM

[193514046726897] Unknown error :/usr/local/lib/python3.12/site-packages/midealocal/device.py, 415, RefreshFailed()
```

**Comment by flamestsui** [comment]
@wuwentao v0.4.1，期待大佬搞定

**Comment by chemelli74** [comment]
Please check with v0.4.3 and if still experience the issue, add the following to `configuration.yaml` , restart HA, and post the log:
```yaml
logger:
  default: warning
  logs:
    custom_components.midea_ac_lan: debug
    midealocal: debug
 ```
Note: it is better to drag the log into the comment (which will add it as an attachment) and not copy paste as it is hard to read logs in GitHub.

**Comment by flamestsui** [comment]
大佬，求修复啊

**Comment by flamestsui** [comment]
@wuwentao 刚更新了
2024-07-03 00:57:42.028 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '.03', 'body type': '.03'}
2024-07-03 00:57:42.177 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030000000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '.03', 'body type': '.03'}
2024-07-03 00:57:42.178 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030000000000f300ff0f62f1000000ff003200ffda346c6d0092
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 361, in parse_message
    status = self.process_message(bytes(decrypted))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midealocal/devices/da/__init__.py", line 159, in process_message
    self._attributes[status] = softener[getattr(message, str(status))]
                               ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
2024-07-03 00:57:52.200 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '.03', 'body type': '.03'}

**Comment by flamestsui** [comment]
@chemelli74 it v0.4.3 and restart HA
this log at attachment
[ha.log](https://github.com/user-attachments/files/16072722/ha.log)

**Comment by wuwentao** [comment]
> @chemelli74 it v0.4.3 and restart HA this log at attachment [ha.log](https://github.com/user-attachments/files/16072722/ha.log)



> @chemelli74 it v0.4.3 and restart HA this log at attachment [ha.log](https://github.com/user-attachments/files/16072722/ha.log)

thanks, with this error output, it's hard to decode and understand the root cause, I will try to add more debug log output and we can confirm it later.

**Comment by flamestsui** [comment]
@wuwentao thanks

**Comment by flamestsui** [comment]
我的是安装在Exsi里面的。手动输入替换，现在已经好了
@wuwentao

**Comment by flamestsui** [comment]
我的是安装在Exsi里面的。手动输入替换，
`        for status in self._attributes:
            if hasattr(message, str(status)):
                value = getattr(message, str(status))
                if status == DeviceAttributes.progress:
                    self._attributes[status] = (
                        None if value >= len(progress) else progress[value]
                    )
                elif status == DeviceAttributes.program:
                    self._attributes[status] = (
                        None if value >= len(program) else program[value]
                    )
                elif status == DeviceAttributes.rinse_level:
                    temp_rinse_level = value
                    if temp_rinse_level == MIN_TEMP:
                        self._attributes[status] = None
                    else:
                        self._attributes[status] = temp_rinse_level
                elif status == DeviceAttributes.dehydration_speed:
                    self._attributes[status] = (
                        "-" if value >= len(speed) else speed[value]
                    )
                elif status == DeviceAttributes.detergent:
                    self._attributes[status] = (
                        None if value >= len(detergent) else detergent[value]
                    )
                elif status == DeviceAttributes.softener:
                    self._attributes[status] = (
                        None if value >= len(softener) else softener[value]
                    )
                elif status == DeviceAttributes.wash_strength:
                    self._attributes[status] = (
                        "-" if value >= len(strength) else strength[value]
                    )
                else:
                    self._attributes[status] = value
                new_status[str(status)] = self._attributes[status]

        return new_status`
现在已经好了。但是Start的状态还是不对

然后使用Button，无法关闭洗衣机。
[ha.log](https://github.com/user-attachments/files/16107434/ha.log)
@wuwentao

**Comment by flamestsui** [comment]
@wuwentao 更新了0.5.0后，不管是否恢复__init__.py，全部变不可用了

**Comment by wuwentao** [comment]
> @wuwentao 更新了0.5.0后，不管是否恢复__init__.py，全部变不可用了

应该是某个功能报错，所以就变成禁用状态了，按照首页提示，开启midea_ac_lan和midealocal的debug log，然后查看具体的debug log.

我有一个疑问，你这台设备添加时，是否手工修改过protocol或者其他subtype之类的？请勿使用错误的protocol或者配置强行添加设备。
如果你配置文件或者protocol等选错了，在一个错误的配置基础之上，讨论任何操作都是浪费时间和精力的。
目前好几个github issue反馈小天鹅洗衣机无法添加成功，所以请务必确认配置是正确的，之前的旧版本很多人自行修改配置，尤其是出问题以后，来回修改各种参数，试图找出一个可以正常使用的配置，实际是错误的操作。

**Comment by wuwentao** [comment]
got the error msg, my device also have the same result, don't need debug log now.

**Comment by flamestsui** [comment]
@wuwentao  没有手动修改过任何东西， 出之前让我替换__init__.py
![Snipaste_2024-07-10_18-09-01]
[HA.log](https://github.com/user-attachments/files/16159231/HA.log)
(https://github.com/wuwentao/midea_ac_lan/assets/3983453/ed2349ba-b3e2-47be-be3f-fcc60920f282)

**Comment by flamestsui** [comment]
[HA.log](https://github.com/user-attachments/files/16159289/HA.log)
重新设备添加的日志。

**Comment by flamestsui** [comment]
改了__init__.py之后
2024-07-10 18:30:53.788 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Does not supports the protocol MessageQuery, ignored
2024-07-10 18:30:53.788 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Refresh status is timed out
2024-07-10 18:30:53.788 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Status update: {'available': False}
2024-07-10 18:30:58.790 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Connecting to 192.168.88.206:6444
2024-07-10 18:30:58.793 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Connected
2024-07-10 18:30:58.794 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Authentication success
2024-07-10 18:30:58.794 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Sending: {'header': 'aa0bda00000000000003', 'body': '03', 'message type': '.03', 'body type': '.03'}
2024-07-10 18:30:59.394 DEBUG (波轮洗衣机) [midealocal.devices.da] [140737488443965] Received: {'header': 'aa23da00000000000003', 'body': '030000000000f300ff0f62f1000000ff003200ffda346c6d00', 'message type': '.03', 'body type': '.03'}
2024-07-10 18:30:59.395 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Error in process message, msg = aa23da00000000000003030000000000f300ff0f62f1000000ff003200ffda346c6d0092
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 407, in parse_message
    status = self.process_message(bytes(decrypted))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midealocal/devices/da/__init__.py", line 146, in process_message
    None if value >= len(program) else program[value]
            ^^^^^
NameError: name 'value' is not defined. Did you mean: 'False'?
2024-07-10 18:30:59.396 ERROR (波轮洗衣机) [midealocal.device] [140737488443965] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 221
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 221, in connect
    self.get_capabilities(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 329, in get_capabilities
    raise CapabilitiesFailed
midealocal.device.CapabilitiesFailed
2024-07-10 18:30:59.397 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Status update: {'available': False}
2024-07-10 18:31:04.403 DEBUG (波轮洗衣机) [midealocal.device] [140737488443965] Connecting to 192.168.88.206:6444

**Comment by flamestsui** [comment]
替换__init__.py后，日志
[HA.log](https://github.com/user-attachments/files/16159530/HA.log)

**Comment by flamestsui** [comment]
@wuwentao 刚更新了0.5.1
问题如下：
还是使用上面修改的__init__.py

状态可用，点击开始，洗衣机有滴声，但是洗衣机未开启，点击后，按钮状态自动变成关闭。
点击“启动”，能开始洗衣，但是安装状态还是变成关闭。

日志如下：
[HA.txt](https://github.com/user-attachments/files/16163732/HA.txt)

**Comment by wuwentao** [comment]
@flamestsui 新版已无需修改和替换`__init__.py`了，默认已经是修改过的了，之前是新版没release，所以才需要手工改。
直接当前升级最新版即可，启用debug log，执行相关操作，以及实际的设备反应，再提供log确认后续控制和操作上的问题。

**Comment by wuwentao** [comment]
当前issue长时间未收到任何回复或响应，无法确定当前状态和解决结果，因此先直接close issue，如果仍然有相同的问题，后续可以直接reopen。
如果是其他问题，则提交新的issue即可
